シミュレータが起動しない問題の解決
KatLab-MiyazakiUniv/etrobocon2021 pull request #100
Opened 2021-07-16 20:54 UTC by mutotaka0426

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
- BlockSelectorクラスのメンバにある配列の初期化をコンストラクタで行うように変更

# エラーの原因調査
```
  bool OPEN_CIRCLE_ID[static_cast<int>(BLOCK_ID::ID7) + 1][static_cast<int>(CIRCLE_ID::ID7) + 1] = {
          { T, T, T, T, F, F, F, F },
          { F, T, T, F, T, F, F, F },
          { T, T, F, T, F, T, F, F },
          { T, T, T, T, T, F, T, T },
          { T, T, F, T, T, T, T, T },
          { F, F, T, F, T, F, T, T },
          { F, F, F, T, F, T, T, F },
          { F, F, F, F, T, T, T, T }};
```
のように書き換えると解決したらしいので，STLコンテナが何か悪さをしている？

BlockSelectorクラスと同様に，宣言時に配列の初期化をするサンプルコードで試したところ，特にエラーは出なかったため，シミュレータ環境下での問題だと考えられる．
サンプルコードは下図に示す．

![キャプチャ](https://user-images.githubusercontent.com/56989154/126007117-683d6e00-6b53-4f65-b21a-84eade003481.PNG)

## 添付資料

2021-07-17 04:55 UTC, Takahiro55555 approved these changes
シミュレータで無事ゴールすることまで確認しました

![LGTM](https://image.lgtmoon.dev/134357)

2021-07-17 05:18 UTC, miyashita64 approved these changes
ご迷惑をおかけして、すみません...
修正、ありがとうございます。

2021-07-17 05:28 UTC, Takahiro55555 commented on module/BlockSelector.h
> +  const std::array<std::array<bool, static_cast<int>(BLOCK_ID::ID7) + 1>, 8> OPEN_CIRCLE_ID;
```suggestion
  const std::array<std::array<bool, static_cast<int>(BLOCK_ID::ID7) + 1>, static_cast<int>(CIRCLE_ID::ID7) + 1> OPEN_CIRCLE_ID;
```
Approveしてしまったけど、配列の要素数をマジックナンバーに変更したのはなんで？

2021-07-17 05:29 UTC, Takahiro55555 commented on module/BlockSelector.h
> +  const std::array<std::array<bool, 8>, 8> OPEN_BLOCK_ID;
```suggestion
  const std::array<std::array<bool, static_cast<int>(BLOCK_ID::ID7) + 1>, static_cast<int>(BLOCK_ID::ID7) + 1> OPEN_BLOCK_ID;
```
ここも

2021-07-17 10:23 UTC, hiroto0927 approved these changes
修正ありがとうございます。

2021-07-17 14:12 UTC, mutotaka0426 commented on module/BlockSelector.h
> +  const std::array<std::array<bool, static_cast<int>(BLOCK_ID::ID7) + 1>, 8> OPEN_CIRCLE_ID;
キャストしてるのがいけないのかなって思ってマジックナンバーで試したまま，直すの忘れてた
直します

2021-07-17 15:06 UTC, Takahiro55555 commented on module/BlockSelector.h
> +  const std::array<std::array<bool, static_cast<int>(BLOCK_ID::ID7) + 1>,
@hiroto0927 @miyashita64 

この部分は、意味があって`BLOCK_ID`ではなくて`CIRCLE_ID`を使っていた感じ？

2021-07-17 15:31 UTC, miyashita64 commented on module/BlockSelector.h
> +  const std::array<std::array<bool, static_cast<int>(BLOCK_ID::ID7) + 1>,
ブロックサークルについての開放行列なので、CIRCLE_IDを使っています。

2021-07-17 15:44 UTC, Takahiro55555 requested changes

2021-07-17 15:44 UTC, Takahiro55555 commented on module/BlockSelector.h
> +  const std::array<std::array<bool, static_cast<int>(BLOCK_ID::ID7) + 1>,
@mutotaka0426 

```suggestion
  const std::array<std::array<bool, static_cast<int>(CIRCLE_ID::ID7) + 1>,
```

すまん、自分の提案が間違ってたみたいや...

修正お願いします🙇‍♂️

2021-07-18 15:03 UTC, mutotaka0426 commented on module/BlockSelector.h
> +  const std::array<std::array<bool, static_cast<int>(BLOCK_ID::ID7) + 1>,
違いに気づかずコピペしてたわ

2021-07-19 01:24 UTC, arimakaoru approved these changes

2021-07-19 01:25 UTC, sugaken0528 approved these changes

2021-07-19 01:32 UTC, Takahiro55555 approved these changes
![LGTM](https://image.lgtmoon.dev/15799)

2021-07-19 01:32 UTC, merged