Ticket 93
KatLab-MiyazakiUniv/etrobocon2021 pull request #101
Opened 2021-07-17 05:32 UTC by hiroto0927

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
Measurer.cpp
Mesaurer.h
HorizonArm.cpp
HorizonArm.h

# 動作テスト

## 実験方法
回頭させて、Measurerのカウントで値を検証

## 実験結果
改善前は、-32~-1の範囲を動いていた。
改善後は、-40~-48の範囲を動いていた。

## 添付資料
改善前

https://user-images.githubusercontent.com/83230897/126026847-8742a42b-4cfb-433e-b15b-cfa7c1ec632b.mp4

改善後

https://user-images.githubusercontent.com/83230897/126026733-b1a26ffe-6153-43a9-a1ff-4348c9be368e.mp4

2021-07-17 14:24 UTC, mutotaka0426 commented
動画なんだけどカメラを走行体に近づけたやつが見たいな
たしかc押したらカメラ切り替えられるはずだからそれで撮れない？

あと，これってまだレビューしなくていいやつ？

2021-07-17 15:30 UTC, miyashita64 commented
> 動画なんだけどカメラを走行体に近づけたやつが見たいな
> たしかc押したらカメラ切り替えられるはずだからそれで撮れない？

撮り直してみます。
 
> あと，これってまだレビューしなくていいやつ？

これを元に、PID調整を行っていこうと思っているので、見ていただけるとありがたいです。

2021-07-19 02:22 UTC, hiroto0927 commented
動画新しく、走行体に近づけたものへ更新しました。

2021-07-20 10:14 UTC, mutotaka0426 requested changes

2021-07-20 10:14 UTC, mutotaka0426 commented on module/HorizonArm.cpp
> +}
keepArmだから，目標角度になるまでwhile文で回してほしい

2021-07-26 23:39 UTC, sugaken0528 requested changes
動画見た感じめっちゃ良さげやね!

2021-07-26 23:39 UTC, sugaken0528 commented on module/HorizonArm.h
> +  static constexpr int targetArmCount = -45;
TARGET_ARM_COUNT

2021-07-27 06:08 UTC, Hisataka-Hagiyama commented
> ノートPC環境だと初回のカーブでコースアウトしたが、研究室環境だと完走した。

動画は添付できますか？完走するのであればどういう走りをしているのか見たいです。

2021-07-27 17:14 UTC, Takahiro55555 approved these changes
![LGTM](https://image.lgtmoon.dev/75034)

2021-07-28 04:57 UTC, Hisataka-Hagiyama approved these changes
![LGTM](https://image.lgtmoon.dev/109811)

2021-07-28 05:01 UTC, arimakaoru requested changes
だいたいOK！動画も良さそう！

2021-07-28 08:12 UTC, sugaken0528 approved these changes
![LGTM](https://image.lgtmoon.dev/135281)

2021-07-28 08:17 UTC, mutotaka0426 approved these changes
動画見た感じも良さそう！
![LGTM](https://image.lgtmoon.dev/135285)

2021-07-29 00:21 UTC, uchyam approved these changes
LGTM

2021-07-29 02:24 UTC, arimakaoru approved these changes
LGTM!!

2021-07-29 02:29 UTC, merged