close #96 直進の精度調整
KatLab-MiyazakiUniv/etrobocon2021 pull request #103
Opened 2021-07-21 03:52 UTC by hiroto0927

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
StraightRunner.h
StraightRunner.cpp

# 動作テスト

## 実験方法

## 実験結果

## 添付資料

2021-07-26 23:49 UTC, sugaken0528 commented
目標からどれくらいの角度ズレてるか計測できる?
動画見た感じかなり改善されてるのは伝わるけど、できれば修正前と修正後で平均誤差がどれだけ変わったかを数値で示してくれると助かる。動作に関する誤差はモデルで使うから!
スプレッドシートで10回分の誤差とその平均を書いて共有するといいかな。

2021-07-27 05:05 UTC, hiroto0927 commented
> 目標からどれくらいの角度ズレてるか計測できる?
> 
計測するツールの指定とかってありますか？？
なければ分度器で計ろうと思いますが。。。

2021-07-27 05:05 UTC, Hisataka-Hagiyama commented on module/StraightRunner.cpp
> +    // 左右の走行距離を合わせるた補正値計算
修正する程のミスでもない気がしますが気になったので
```suggestion
    // 左右の走行距離を合わせるための補正値計算
```

2021-07-28 05:11 UTC, sugaken0528 commented
角度の計測は分度器でごり押ししか今のとこ浮かばんな、

2021-07-28 06:00 UTC, arimakaoru requested changes
プルリクの「変更点」はもう少し具体的に何をしたか書いてくれないと，コード読むのが大変

2021-07-28 10:29 UTC, hiroto0927 commented on module/StraightRunner.h
> +  static constexpr int SECTION_DISTANCE = 10;  // 調整距離
mmです。

2021-07-28 12:54 UTC, sugaken0528 approved these changes
![LGTM](https://image.lgtmoon.dev/135309)

2021-07-28 13:14 UTC, Hisataka-Hagiyama approved these changes
![LGTM](https://image.lgtmoon.dev/135319)

2021-07-28 23:36 UTC, uchyam commented on module/StraightRunner.cpp
> +    printf("%d\n", currentPwm);
これはテスト用ですか？

2021-07-29 02:33 UTC, arimakaoru approved these changes
LGTM!!
公式を変えちゃったけど，変更後でもちゃんと動くことを確認したよね？
PWM=100のときの平均誤差がめっちゃ小さくなってて素晴らしい！これなら安心してApprove出せる！

2021-07-29 06:08 UTC, kodama0720 approved these changes
LGTM

2021-07-29 06:32 UTC, Takahiro55555 approved these changes
LGTM!!!

2021-07-29 06:33 UTC, merged