close #97 回頭・ピボットターンの精度調整
KatLab-MiyazakiUniv/etrobocon2021 pull request #107
Opened 2021-07-25 14:47 UTC by yutotanaka24

# チェックリスト

- [] clang-format している
- [] コーディング規約に準じている
- [] チケットの完了条件を満たしている

# 変更点
-Rotation.cppの回頭とピボットターンに、目標値に近づくにつれPWM値を徐々に小さくしていく処理を追加
-回頭での両方のタイヤを止める条件を片方の足に合わせた
# 動作テスト
-明日動画を乗せようと思っています（間に合わず申し訳ありません）
## 実験方法
-
## 実験結果

## 添付資料

2021-07-26 05:07 UTC, Hisataka-Hagiyama reviewed
チェックリストの項目を確認して、大丈夫であれば忘れずにチェックを入れておいてください。

2021-07-26 05:07 UTC, Hisataka-Hagiyama commented on module/EtRobocon2021.cpp
> +    //ライントレースエリア攻略開始
リモートのmainブランチにあるEtrobocon2021.cppと改行が違いませんか？

2021-07-26 05:07 UTC, Hisataka-Hagiyama commented on module/EtRobocon2021.h
> -
ここも改行が消えてます

2021-07-27 03:30 UTC, mutotaka0426 commented on module/Rotation.h
> +  static constexpr double DIAMETER = 310.0; //ピボットターンの円の直径
ピボットターンの円の直径ってトレッド幅×2じゃないの？
310ってどこから来た数字？

2021-07-27 05:13 UTC, Hisataka-Hagiyama commented
各PWM値についてどれくらいの精度で回るのか測ると
>PWM値をある程度限定すれば高い精度で回れると思う。

の部分が明確になるのではないでしょうか？

2021-07-27 14:21 UTC, Takahiro55555 requested changes

2021-07-27 14:21 UTC, Takahiro55555 commented on module/Rotation.cpp
> +  double distance = (DIAMETER - 5) * M_PI * angle / 360;  //弧の長さ
`DIAMETER - 5`にしているのは、このほうが上手くいくから？

ここは、マジックナンバーにしないほうが良いかも

2021-07-27 14:21 UTC, Takahiro55555 commented on module/Rotation.cpp
> +  double distance = (DIAMETER - 5) * M_PI * angle / 360;  //弧の長さ
ここも、`DIAMETER - 5`にしているのは、このほうが上手くいくから？

上と同様に、マジックナンバーにしないほうが良いかも。

2021-07-27 23:32 UTC, yutotanaka24 commented on module/Rotation.h
> +  static constexpr double DIAMETER = 310.0; //ピボットターンの円の直径
今までトレッド幅の2倍でやってたんですが、それだと設定した角度（弧の距離）に届かないことが多かったので、そもそも直径が実際はもう少し大きいのではと思って変えました。
310は、調整していたらただ上手くいったからこの数値にしました。

2021-07-27 23:33 UTC, yutotanaka24 commented on module/Rotation.cpp
> +  double distance = (DIAMETER - 5) * M_PI * angle / 360;  //弧の長さ
同じピボットターンなのに直径が違うのはおかしいなと思いましたが、とりあえずうまくいく数値だったからー5してます。。

2021-07-28 10:18 UTC, Takahiro55555 commented on module/Rotation.cpp
> +  double distance = (DIAMETER - 5) * M_PI * angle / 360;  //弧の長さ
せめて、ソースコードにコメントを残しておくとよいかも

2021-07-28 10:54 UTC, mutotaka0426 commented on module/Rotation.h
> +  static constexpr double DIAMETER = 310.0; //ピボットターンの円の直径
トレッド幅を135に調整してるのは良いとしても，ピボットターンの円の直径がトレッド幅×2より大分差があるのは気になるな

ピボットターンの時，軸足が少し前進してしまうから回転角度が足りないってことが去年はあったんだけど，似たような現象ではない？去年は軸足の方のpwmを-1にしてピボットターンしてたんだけど

2021-08-11 06:37 UTC, merged