Update: アームを水平に保つ処理をタスクに追加
KatLab-MiyazakiUniv/etrobocon2021 pull request #122
Opened 2021-08-04 13:32 UTC by hiroto0927

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
app.cpp
HorizonArm.cpp
HorizonArm.h
ArmMotion.h
ArmMotion.cpp

# 動作テスト

## 実験方法
回頭（360°）を実行後、投げ入れ設置を行う。
この際、アームが水平に保たれている事を確認する。

## 実験結果
回頭を行う際は、アームを水平に保つことができた。
投げ入れ設置を行う際は、アームを水平に保つ処理を行わないようにすることができた。

## 添付資料

https://user-images.githubusercontent.com/83230897/128189539-79ea3727-7a35-4e83-b44e-94ab995f1058.mp4

2021-08-04 15:10 UTC, Hisataka-Hagiyama reviewed
issue(#114 )には 

> ライントレースと各ビンゴ動作を行い、アームが水平に保てているか確認する

とありましたが今後確認をされる予定ですか？(openになってたのでレビューしましたが、もし完了前だったら申し訳ないです)

2021-08-04 15:10 UTC, Hisataka-Hagiyama commented on module/HorizonArm.h
> +  static bool onKeep;
Keepの前にonがあるのは不自然な気もしますが(文法としてはKeep onが正しいはず、、)、他の方が特に気にならないならこのままでもよいと思います。

2021-08-05 02:44 UTC, arimakaoru requested changes
タスクの仕組みがちゃんとわかってないので、的外れなところがあるかも！

2021-08-05 02:44 UTC, arimakaoru commented on module/HorizonArm.cpp
> +    }
現在のkeepArm関数は、タスクとして並列処理することを前提として書かれている。
そのため、タスク以外の場所で呼び出せない（無限ループになる）。
keepArm関数の再利用性を高めるために、タスクとして並列処理するかどうかに関係なく、純粋にアームを水平にするだけの関数にしてほしい。

```suggestion
    int currentCount = measurer.getArmMotorCount();
    if(currentCount == HORIZONTAL_ARM_COUNT) break;
    controller.setArmMotorPwm(pid.calculatePid(currentCount));
```

while文の前で、
`if(onKeep == false) return;`

2021-08-05 02:44 UTC, arimakaoru commented on module/HorizonArm.cpp
> +  // タスクとして並列処理
タスクとして並列処理されることを前提として、keepArm関数を作成すると、再利用性が低く、他の場所で呼び出しづらい。

2021-08-05 02:44 UTC, arimakaoru commented on app.cpp
> +  HorizonArm::keepArm();
上手くできるかわからないけど、ここでループする方が、keepArm関数の再利用性が高くなると思う。
```suggestion
  while(true) {
    HorizonArm::keepArm();
  }
```

2021-08-05 02:44 UTC, arimakaoru commented on module/ArmMotion.cpp
> +  HorizonArm::setOnKeep(false);
この処理をしないと、アームを上げることができないの？

2021-08-05 02:47 UTC, arimakaoru commented
レビューしていい状態なら、左側にあるReviewersからレビューリクエストを送ってね

2021-08-05 06:23 UTC, hiroto0927 commented
> issue(#114 )には
> 
> > ライントレースと各ビンゴ動作を行い、アームが水平に保てているか確認する
> 
> とありましたが今後確認をされる予定ですか？(openになってたのでレビューしましたが、もし完了前だったら申し訳ないです)
単純に、忘れてました。
確認して、動画上げます。

2021-08-09 12:56 UTC, arimakaoru reviewed
だいたい良さそう！

2021-08-09 12:56 UTC, arimakaoru commented on module/ArmMotion.cpp
> +  controller.sleep();
このsleepっているの？

2021-08-09 15:37 UTC, miyashita64 commented on module/ArmMotion.cpp
> +  controller.sleep();
keepFlagがfalseのときは、whileを通らないためsleepされず、タスク側のwhileで無限ループになっているようだったので書きました。（走行体がしばしば止まるような挙動）
タスク側にcontrollerをincludeしてsleepするのも汚いと思ったので、ここに書いています。

2021-08-09 15:38 UTC, Takahiro55555 approved these changes
@arimakaoru が指摘した部分以外は大丈夫だと思います!!!

![LGTM](https://image.lgtmoon.dev/110047)

2021-08-09 15:42 UTC, Takahiro55555 commented on module/ArmMotion.cpp
> +  controller.sleep();
自分は、
>keepFlagがfalseのときは、whileを通らないためsleepされず、タスク側のwhileで無限ループになっているようだったので書きました。（走行体がしばしば止まるような挙動）

を解決するために、`app.cpp`に書かれている`arm_task`中のループの中で10ミリ妙スリープ(`tslp_tsk(10);`)を入れているのかと思ったけど、`app.cpp`に書かれているスリープ処理の目的は違う感じ？

2021-08-09 16:57 UTC, miyashita64 commented on module/ArmMotion.cpp
> +  controller.sleep();
同じ目的ですが、sleepを消した場合、なぜか、シミュレータ内の処理が一時的に重くなります(タイムの進み方が不安定)。

https://user-images.githubusercontent.com/83441177/128744183-d274fb1d-b59d-4e35-9ec6-8c8d5501eba6.mp4

2021-08-10 04:19 UTC, arimakaoru requested changes

2021-08-10 04:19 UTC, arimakaoru commented on module/ArmMotion.cpp
> +  controller.sleep();
app.cppの16行目で使っているtslp_tsk関数の引数は、ミリ秒ではなく、マイクロ秒だと思う。
だから、ここのsleepをなくすと、10マイクロ秒しかスリープせず、負荷が高くなり、TimeScaleが下がっているんじゃないかな。

この対策を試してみて！
app.cppの16行目をマイクロ秒で指定する。
`tslp_tsk(10 * 1000);`

参考（はっきりと書かれた資料が見つからなかった...）
https://github.com/ETrobocon/etrobo/wiki/api_ev3rt_on_athrill#Clock%E3%82%AF%E3%83%A9%E3%82%B9

2021-08-10 04:19 UTC, arimakaoru commented on app.cpp
> +    tslp_tsk(10);  // 10ミリ秒スリープ
```suggestion
    tslp_tsk(10 * 1000);  // 10ミリ秒スリープ
```

2021-08-10 04:59 UTC, Hisataka-Hagiyama commented on module/ArmMotion.h
> + * @author kodama0720, yutotanaka24, hiroto0927, miyashita6
変更しなくても処理に影響は出ないとは思いますが他コードと一貫性を持たせた方がいいかもしれません
```suggestion
 * @author kodama0720, yutotanaka24, hiroto0927, miyashita64
```

2021-08-10 05:04 UTC, Hisataka-Hagiyama reviewed
必須の修正ではないと思いますが統一性を持たせるために変更して頂けるとありがたいです。

2021-08-10 05:04 UTC, Hisataka-Hagiyama commented on module/ArmMotion.h
> + * @author kodama0720, yutotanaka24, hiroto0927, miyashita6
変更しなくても処理に影響は出ないとは思いますが他コードと一貫性を持たせた方がいいかもしれません
```suggestion
 * @author kodama0720, yutotanaka24, hiroto0927, miyashita64
```

2021-08-10 06:25 UTC, mutotaka0426 approved these changes
他の人の指摘箇所が修正されたら自分からは特にいうことないです
![LGTM](https://image.lgtmoon.dev/133971)

2021-08-10 18:54 UTC, miyashita64 commented on module/ArmMotion.cpp
> +  controller.sleep();
以下のように変更すると、しばしば止まるようになりました。
- app.cppのarm_taskのwhile内にtslp_tsk(10 * 1000)
- keepArm()のwhile外にcontroller.sleep() を書かない

https://user-images.githubusercontent.com/83441177/128912830-e44ca101-7e7f-4fc9-a6b9-990ce80b3eb1.mp4

各処理にprintfを加え並列処理ができているか確認したところ、正常に並列化できているようでした。
- LineTracerのwhile内(LINE TRACE: モーターカウント)
- KeepArmのwhile内(=========ARM MOTION: アームモータカウント)
- KeepArmのwhile外(*** ARM END ***)
(※double型のモーターカウントを%dで表示してしまったためおかしな表示になっていますが、走行に合わせて変動していることは確認できました)

![arm_sleep_console](https://user-images.githubusercontent.com/83441177/128912910-7ac6a7ac-5f1c-4acd-a672-86c6a94f2e7a.png)

tslp_tskの挙動が怪しい気がするので、ArmMotion側だけでsleepしようと思いますが、タスク側のループでsleepしないのは問題ですか？

ひとまず、正常な動作を確認できた以下の状態でpushしています。
- app.cppのarm_taskのwhile内にtslp_tsk() を書かない
- keepArm()のwhile外にcontroller.sleep() を書く

2021-08-11 05:47 UTC, Hisataka-Hagiyama approved these changes
自分が修正をお願いした点は修正されていたので大丈夫です
![LGTM](https://image.lgtmoon.dev/136746)

2021-08-11 06:34 UTC, arimakaoru approved these changes
LGTM!!

2021-08-11 06:38 UTC, merged