close #115 経路計画の具体化
KatLab-MiyazakiUniv/etrobocon2021 pull request #123
Opened 2021-08-04 16:00 UTC by hiroto0927

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
RoutePlanner.cpp
RoutePlanner.h
RoutePlannerTest.cpp

経路計画の追加
RoutePlannerクラスに経路計算の処理を追加
全てのブロックサークルにブロックが置かれているかのテストコードの作成

# 動作テスト

## 実験方法
全てのブロックサークルにブロックが置かれていることを確認するテストを行う。
全ての交点サークルにブロックが置かれていないことを確認するテストを行う。

## 実験結果
グーグルテストの通過を確認できた。

## 添付資料

2021-08-05 08:01 UTC, miyashita64 commented on module/RoutePlanner.cpp
> +  robot.setDirection(static_cast<Direction>((dx + 1) + (dy + 1) * 3));
最新経路３つから、ピボット設置か投げ入れ設置かを判定して、方向を算出

2021-08-09 13:16 UTC, arimakaoru requested changes
テストコードがコミットされてない...？

2021-08-09 13:16 UTC, arimakaoru commented on module/RoutePlanner/RoutePlanner.cpp
> +    int dd = static_cast<int>(goal.second) - static_cast<int>(prevGoal.second);
`dd`はちょっと省略しすぎじゃない？
個人的には、変数名はちょっとくらい長くても、読みやすさを優先して良いと思ってる。
Difference in directionのだろうから、`diffDirection`とはどう？

2021-08-09 15:19 UTC, Takahiro55555 reviewed
自分からはコードに関する指摘はありません。

テストコードがPushされたら再度確認します。

2021-08-09 19:50 UTC, Takahiro55555 approved these changes
LGTM!!!

![LGTM](https://image.lgtmoon.dev/110047)

2021-08-10 04:31 UTC, arimakaoru approved these changes
![LGTM](https://image.lgtmoon.dev/136580)

2021-08-10 08:09 UTC, uchyam approved these changes
LGTM

2021-08-10 08:18 UTC, mutotaka0426 approved these changes
取り合えずこのチケットはokです．お疲れ様！

あとは，計算したフルビンゴまでの経路をどこかしらに保持しとかないといけないから，それだけ覚えておいてほしい．どういう形式でどこが保持するかとかがまだ決まってないから，このチケットではやらなくて大丈夫です．

![LGTM](https://image.lgtmoon.dev/90696)

2021-08-10 11:57 UTC, merged