動作実行[Draft]
KatLab-MiyazakiUniv/etrobocon2021 pull request #125
Opened 2021-08-05 04:28 UTC by uchyam

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
動作実行クラスであるMotionPerformer.h、MotionPerformer.cppを作成
動作実行クラス内に、全７種類のビンゴ動作に対して、以下の関数（21個）を実装
- ビンゴ動作を呼び出して、履歴をとる関数
- ビンゴ動作の時間コストを取得する関数
- ビンゴ動作の誤差コストを取得する関数

# 動作テスト
- このクラスを通してビンゴ動作を呼び出せているか確認できる動画をとる
- テストコードにて正しく履歴が取れているかを確認する

## 実験方法

## 実験結果

## 添付資料

2021-08-10 06:57 UTC, kodama0720 requested changes

2021-08-10 06:57 UTC, kodama0720 commented on module/MotionPerformer.h
> +#include "vector"
個人的には<>で書いてほしいです
`#include <vector>`

2021-08-10 06:57 UTC, kodama0720 commented on test/MotionPerformerTest.cpp
> +    }
i , i2, i3は同じ変数でいいと思います

2021-08-10 06:57 UTC, kodama0720 commented on module/MotionPerformer.cpp
> +    if(angle>0){
式にスペースを入れてほしいです

2021-08-10 07:31 UTC, Hisataka-Hagiyama commented on module/MotionPerformer.h
> +#include "vector"
その理由ってやっぱりライブラリを""で囲むより<>の方がコンパイル時間が短くなるからですか？それとも見た目を統一するという目的ですか？<>で囲んだ方がコンパイル時間が体感できないくらいのレベルではありますが短くなるとかだった気がしますが

2021-08-10 08:28 UTC, mutotaka0426 commented on module/MotionPerformer.h
> +#include "vector"
調べたら，`<>`でくくる場合はコンパイラに設定されてるパスから探してきて，`""`でくくる場合はカレントディレクトリから探して，なければコンパイラに設定されてるパスから探してくるらしいね．知らなかった．

早さに関してはぶっちゃけ大差ないと思うけど，標準ライブラリってことを分かりやすくするためにも`<>`にした方がいいね

2021-08-10 10:50 UTC, mutotaka0426 requested changes
履歴をstaticにしてほしいってところ以外は基本的にはok
後は細かいところだけ

2021-08-10 10:50 UTC, mutotaka0426 commented on test/MotionPerformerTest.cpp
> +    std::vector<MOTION> motionLog;
これは何のためにあるの？

2021-08-10 10:50 UTC, mutotaka0426 commented on module/MotionPerformer.h
> +  std::vector<MOTION> motionLog;
仮に別のMotionPerformerインスタンスから動作実行されても，同じところに記録したいからstaticの方がいいかな？
```suggestion
  static std::vector<MOTION> motionLog;
```

これだけだとエラーなるから，以下を.cppに追加したらビルドが通ることは確認しました
```
std::vector<MOTION> MotionPerformer::motionLog = {};
```

### 参考文献
http://www.toshioblog.com/archives/26674966.html

2021-08-10 10:50 UTC, mutotaka0426 commented on test/MotionPerformerTest.cpp
> +    EXPECT_EQ(motionPerformer.motionLog, expected_motionLog);
motionLogをstaticにした場合はこうかな
```suggestion
    EXPECT_EQ(motionPerformer::motionLog, expected_motionLog);
```

2021-08-10 10:50 UTC, mutotaka0426 commented on test/MotionPerformerTest.cpp
> +    expected_motionLog.push_back(MOTION::TSETL);
BCとPSETLとTSETRのテストができてないんじゃない？

ここはenumで定義してる順にテストしてくれると，ちゃんと全部テスト出来てるかとか見やすくて助かる

2021-08-10 10:50 UTC, mutotaka0426 commented on module/MotionPerformer.h
> +  TSETL = 7,  //(投げ入れ設置:Throw Set Left)
この4つはどこの頭文字取ってるの？右側のコメントアウトを見てもわからないんだけど

2021-08-10 10:59 UTC, mutotaka0426 commented on test/MotionPerformerTest.cpp
> +    expected_motionLog.push_back(MOTION::TSETL);
BCは追加してくれてたわ

2021-08-10 11:03 UTC, mutotaka0426 requested changes
MotionPerformerは`module/BingoMotion/`下に移動しておいて
言ってなかったわごめん！

2021-08-10 11:24 UTC, uchyam commented on module/MotionPerformer.h
> +  TSETL = 7,  //(投げ入れ設置:Throw Set Left)
**P**ivot Turn **Set** **R**ight -> RSETR
**T**hrow  **Set** **R**ight -> TSETR
です
コメント書き換えておきます

2021-08-10 13:14 UTC, Takahiro55555 approved these changes
LGTM!!!

![LGTM](https://image.lgtmoon.dev/110047)

2021-08-10 13:43 UTC, hiroto0927 commented
MotionPerformerのテストについて質問なんですが、直接expected_motionLogにビンゴエリアの動作の番号を入れたものと、 motionPerformerの関数を呼び出してログを取ったものが正しくできているか見ているという理解であってますか？

2021-08-10 13:52 UTC, mutotaka0426 approved these changes
90度と135度のテストは残してくれててよかったけど，まぁいいや
お疲れ様！
![LGTM](https://image.lgtmoon.dev/15784)

2021-08-10 14:39 UTC, uchyam commented
> MotionPerformerのテストについて質問なんですが、直接expected_motionLogにビンゴエリアの動作の番号を入れたものと、 motionPerformerの関数を呼び出してログを取ったものが正しくできているか見ているという理解であってますか？

2021-08-10 14:45 UTC, hiroto0927 approved these changes
LGTM

2021-08-10 17:39 UTC, sugaken0528 requested changes

2021-08-10 17:41 UTC, sugaken0528 requested changes
動作実行クラスのメソッド名は混乱を招くと思うからビンゴ動作のメソッド名に合わせた方が良いと思われる。

2021-08-10 17:41 UTC, sugaken0528 commented on module/BingoMotion/MotionPerformer.h
> +   * @brief 180度方向転換を実行する
180度でしか方向転換しないみたいになってる

2021-08-10 17:41 UTC, sugaken0528 commented on module/BingoMotion/MotionPerformer.h
> +   * @brief 180度方向転換の時間コストを取得
180度でしか方向転換しないみたいになってる

2021-08-10 17:41 UTC, sugaken0528 commented on module/BingoMotion/MotionPerformer.h
> +   * @brief 180度方向転換の誤差コストを取得
180度でしか方向転換しないみたいになってる

2021-08-10 17:41 UTC, sugaken0528 commented on module/BingoMotion/MotionPerformer.h
> +};
ビンゴ動作にメソッド名合わせる時ここの変更も忘れずに

2021-08-11 06:43 UTC, kodama0720 approved these changes
LGTM

2021-08-11 06:51 UTC, sugaken0528 requested changes

2021-08-11 06:51 UTC, sugaken0528 commented on module/BingoMotion/MotionPerformer.cpp
> +void MotionPerformer::pivotTurn(bool isClockwise)
setBlockPivotTurn

2021-08-11 06:51 UTC, sugaken0528 commented on module/BingoMotion/MotionPerformer.h
> +  void pivotTurn(bool isClockwise);
setBlockPivotTurn

2021-08-11 06:51 UTC, sugaken0528 commented on test/MotionPerformerTest.cpp
> +    motionPerformer.pivotTurn(false);
setBlockPivotTurn

2021-08-11 07:16 UTC, sugaken0528 commented
シミュレータテスト通ってないのはなんでだ??

2021-08-11 07:17 UTC, Hisataka-Hagiyama commented
> 
> 
> シミュレータテスト通ってないのはなんでだ??

` rm: cannot remove '/tmp/tmp.OHCYk089tb': Directory not empty`

っていうエラーが起きてるみたいです

2021-08-11 07:56 UTC, mutotaka0426 requested changes

2021-08-11 07:56 UTC, mutotaka0426 commented on module/BingoMotion/MotionPerformer.cpp
> +void MotionPerformer::throwBlock(bool isClockwise)
setBlockPivotTurnと合わせたほうがいいから以下のようにした方がよくない？
だからBlockThrowerクラスの関数名もsetBlockThrowに変更してください
```suggestion
void MotionPerformer::setBlockThrow(bool isClockwise)
```

2021-08-11 07:56 UTC, mutotaka0426 commented on module/BingoMotion/MotionPerformer.h
> +  TSETL = 7,  //(左回転投げ入れ設置:Throw SET Left)
こうじゃない？
```suggestion
  SBPR = 4,  //(右回転ピボットターン設置:Set Block Pivot turn Right)
  SBPL = 5,  //(左回転ピボットターン設置:Set Block Pivot turn Left)
  SBTR = 6,  //(右回転投げ入れ設置:Set Block Throw Right)
  SBTL = 7,  //(左回転投げ入れ設置:Set Block Throw Left)
```

2021-08-11 08:33 UTC, mutotaka0426 commented on module/BingoMotion/MotionPerformer.cpp
>    blockThrower.throwBlock(isClockwise);
BlockThrowerクラスの関数名もsetBlockThrowに変更よろしくお願いします

2021-08-11 09:36 UTC, sugaken0528 approved these changes
LGTM

2021-08-11 09:50 UTC, merged