This commit is for ticket-132 [Draft]
KatLab-MiyazakiUniv/etrobocon2021 pull request #148
Opened 2021-08-24 09:05 UTC by Hisataka-Hagiyama

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点

# 動作テスト

## 実験方法

## 実験データ

|  修正前  |  修正後  |
| ---- | ---- |
|  -  |  -  |
|  -  |  -  |

## 実験結果

## 添付資料

2021-08-28 10:00 UTC, mutotaka0426 requested changes
処理については一箇所以外突っ込むところなさそうです

↓ここからは，まだ判断つかないから相談とメモついでに書いとくけど，今回のチケットでは見てくれるだけでいいよ．

経路計画で求める運搬経路リストは取得経路と設置経路を合体させた経路のリストの方がいいかな？
今は[取得経路]→[設置経路]→[取得経路]→…って感じかな？違いは以下のようになると思う．

- 取得経路と設置経路を分ける場合(現状)

  - ブロックを取得した後に方向転換をする
  - ブロックを取得した状態で方向転換すると外れるかもしれない
  - 今のコードだとブロックを持ったまま180度回頭する可能性がある？
  - ブロックを持っているときだけ180度回頭を禁じるのは，ちょっと実装が面倒そう

- 取得経路と設置経路を合体させる場合
  - ブロックを交点内移動で取得するようになる
  - 方向転換は取得経路の最初だけでする
  - 交点内移動の中に後退する処理はないので，経路計算で後退しないような経路を選ぶ必要がある
  - 経路計算の中で移動コストを求める処理を実装すれば解決しそう
  - 交点内移動の中に後退する処理を追加してもいいかも（あんまりやりたくない）

2021-08-28 13:12 UTC, arimakaoru approved these changes
LGTM!!

2021-08-28 17:41 UTC, Takahiro55555 approved these changes
![LGTM](https://image.lgtmoon.dev/110047)

2021-08-28 18:20 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/3111)

2021-08-28 20:33 UTC, sugaken0528 commented on module/RoutePlanner/RoutePlanner.cpp
> +  std::vector<std::vector<std::pair<Coordinate, Direction>>> carryRoute(16);  //運搬経路リスト
これって取得経路と設置経路を合計したやつだよね?
経路の要素数が16の理由ってあったりする?

2021-08-28 23:58 UTC, Hisataka-Hagiyama commented on module/RoutePlanner/RoutePlanner.cpp
> +  std::vector<std::vector<std::pair<Coordinate, Direction>>> carryRoute(16);  //運搬経路リスト
現状取得経路と設置経路を別々に保持しているため8(ブロックの数)*2(取得経路、設置経路)=16としています。
@mutotaka0426 のコメントにあるように、取得経路と設置経路を合体させる方針となるとここが8になると思います。

2021-08-29 00:33 UTC, miyashita64 approved these changes
LGTM!

2021-08-29 03:40 UTC, merged