close #164 ピボットターンの再調整
KatLab-MiyazakiUniv/etrobocon2021 pull request #173
Opened 2021-09-01 15:06 UTC by hiroto0927

# チェックリスト

- [] clang-format している
- [] コーディング規約に準じている
- [] チケットの完了条件を満たしている

# 変更点
ピボットターンの全動作を去年のものに、再度調整

# 動作テスト

## 実験方法

Uploading ETロボコンシミュレータ 2021-09-01 23-25-35.mp4…

実際にビンゴエリア内にてピボットターンを使う動作を行う。

## 実験結果

## 添付資料

2021-09-02 11:21 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/89932)

2021-09-02 11:44 UTC, Takahiro55555 requested changes

2021-09-02 12:17 UTC, arimakaoru commented
結局、試走会の環境では良い精度だった？
あと動画のシミュレータのバージョンが古いよ

2021-09-02 13:35 UTC, hiroto0927 commented on module/Motion/Rotation.cpp
> +  // @see docs/Odometry/odometry.pdf
去年のコードを書き写した為、正確には理解していませんがオドメトリドメ手法というものです。

https://shogo82148.github.io/homepage/memo/tenchijin/odmetry.html

2021-09-02 14:02 UTC, arimakaoru commented
重要なことだから確認するけど、「検証したPCと試走会の環境でピボットターンの精度に大きな差はない」ということでいい？

2021-09-02 14:08 UTC, hiroto0927 commented
差はないと思います。黒ブロックは、今プッシュされているものを取り込み動作確認しましたが動いています。念のため、さっき、もう一度試走会環境に投げています。

2021-09-02 14:10 UTC, arimakaoru commented
OK!大きな問題が解決かな！

2021-09-03 02:39 UTC, arimakaoru approved these changes
現在のmainブランチでは、sim-settings/default.jsonは正しく設定されているから、sim-settings/default.jsonの変更はいらないんじゃない？
@Takahiro55555 どうなの？

2021-09-03 16:16 UTC, hiroto0927 commented
ピボットターンのテストは、去年のコードを参考に誤差が1.5になるように確かめています。
前方向は全て通りましたが、後ろ方向が通りません。
アドバイスお願いします。

https://github.com/KatLab-MiyazakiUniv/etrobocon2020/blob/master/test/RotationTest.cpp

2021-09-04 13:34 UTC, Takahiro55555 approved these changes
LGTM!!!

2021-09-05 02:39 UTC, sugaken0528 approved these changes

2021-09-05 02:39 UTC, merged