close #17 走行距離を計算する
KatLab-MiyazakiUniv/etrobocon2021 pull request #25
Opened 2021-05-27 08:25 UTC by uchyam

# チェックリスト
- [x] clang-formatしている
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている
# 変更点
- 走行距離を計算するクラスを追加

2021-05-27 09:28 UTC, Takahiro55555 submitted a review, later dismissed
LGTM!!!
![LGTM](https://image.lgtmoon.dev/74964)

2021-05-28 02:46 UTC, arimakaoru reviewed
OK!
強いて言えば、ここら辺を修正した方がいいかな〜

2021-05-28 02:46 UTC, arimakaoru commented on module/Mileage.h
> +  double radius;  //タイヤの半径[mm]
```suggestion
  const double radius;  //タイヤの半径[mm]
```
「タイヤの半径」は変わることのない値なので、`const`を付けて、プログラム中で変更できないようにしましょう。
constを付けると、間違ってこの変数を書き換える処理を書いたときに、コンパイルエラーで教えてくれるため、予期せぬバグを防ぐことに繋がります。

2021-05-28 02:46 UTC, arimakaoru commented on module/Mileage.cpp
> + *  @author Hisataka-Hagiyama,uchiyam
`uchiyam`は、GitHubのユーザ名を書いてる？
だとしたら、iは付いてないよ
まあ、ここは何でもいいけどね！

2021-05-28 11:44 UTC, mutotaka0426 commented on module/Mileage.h
> +#define DISTANCE_H
クラス名のアッパースネークケースで統一します！

2021-05-28 12:01 UTC, mutotaka0426 commented on module/Mileage.h
> +  double calculateWheelMileage(int angle);
処理自体はいいんだけど，この関数って他クラスで使う予定ある？
使う予定はないか，もしくはまだ分からないのであれば，privateに移してカプセル化しておいた方がいいと思う
使うならこのままでいいよ

2021-05-31 09:58 UTC, Takahiro55555 submitted a review, later dismissed
![LGTM](https://image.lgtmoon.dev/122126)

2021-06-01 02:53 UTC, mutotaka0426 approved these changes
シングルトン採用してくれたのね
ありがとう

![LGTM](https://image.lgtmoon.dev/123956)

2021-06-02 03:25 UTC, arimakaoru approved these changes
OK!お疲れ様！

2021-06-02 09:46 UTC, kodama0720 submitted a review, later dismissed
LGTM

2021-06-02 10:42 UTC, sugaken0528 requested changes

2021-06-02 10:42 UTC, sugaken0528 commented on test/MileageTest.cpp
> +    double leftWheel = 2 * 20 * 45 * M_PI / 360;
```suggestion
    double rightWheel = 2 * radius * rightAngle * M_PI / 360;
    double leftWheel = 2 * radius * leftAngle * M_PI / 360;
```
マジックナンバーは使わない方が良いと思われる

2021-06-02 10:42 UTC, sugaken0528 commented on test/MileageTest.cpp
> +    double leftWheel = 2 * -20 * 45 * M_PI / 360;
上に同じく

2021-06-02 10:42 UTC, sugaken0528 commented on test/MileageTest.cpp
> +    double leftWheel = 2 * 0 * 45 * M_PI / 360;
上に同じく

2021-06-02 13:08 UTC, sugaken0528 approved these changes
ないっすう！

2021-06-02 13:09 UTC, arimakaoru approved these changes
OK!

2021-06-02 13:46 UTC, miyashita64 approved these changes
LGTM

2021-06-02 14:16 UTC, yutotanaka24 approved these changes

2021-06-02 19:06 UTC, hiroto0927 approved these changes

2021-06-03 05:00 UTC, etckanikama commented
処理とかよさそうな気がしたんですけど，手計算との検証とかってしたのかなって気になりました....

2021-06-03 05:50 UTC, Takahiro55555 approved these changes

2021-06-03 06:42 UTC, merged