close #13 PIDを計算する
KatLab-MiyazakiUniv/etrobocon2021 pull request #26
Opened 2021-05-27 08:26 UTC by Hisataka-Hagiyama

# チェックリスト
- [x] clang-formatしている
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている
# 変更点
- Pid.hを追加した
- Pid.cppを追加した
- PidTest.cppを追加した
- Makefileに追加したクラスを記述した

2021-05-27 09:33 UTC, Takahiro55555 commented on test/PidTest.cpp
> +  }
きちんと値を変更できているかの確認をした方が良い気がする。  
けど、そしたら新たに Getter を作らないといけなそう...   

@arimakaoru @mutotaka0426 @sugaken0528 
どうするのが良いと思いますか？

2021-05-28 03:33 UTC, arimakaoru requested changes
いくつか悩ましいところがあるね...

2021-05-28 03:33 UTC, arimakaoru commented on test/PidTest.cpp
> + *  @author Hisataka-Hagiyama,uchiyam
```suggestion
 *  @author Hisataka-Hagiyama,uchyam
```

2021-05-28 03:33 UTC, arimakaoru commented on module/Pid.h
> + *  @author Hisataka-Hagiyama,uchiyam
```suggestion
 *  @author Hisataka-Hagiyama,uchyam
```

2021-05-28 03:33 UTC, arimakaoru commented on module/Pid.cpp
> + *  @author Hisataka-Hagiyama,uchiyam
```suggestion
 *  @author Hisataka-Hagiyama,uchyam
```

2021-05-28 03:33 UTC, arimakaoru commented on module/Pid.h
> +static const double DELTA = 0.01;  //周期[10ミリ秒]
他クラスでも周期を使うだろうから、グローバル変数にしてる？
これは悩ましいね...。
あんまり使わない気がするし、使うとしてもこのファイルで書くことではない気がするんだよね...。
ここはメンバ変数にするか、cluculatePid関数の中で宣言してもいいかな〜
悩ましい...。
@Takahiro55555 @sugaken0528 @mutotaka0426 他の意見待ち

2021-05-28 03:33 UTC, arimakaoru commented on test/PidTest.cpp
> +  }
うーん...テストのためだけにGetter作るのは嫌だから、setしてclacするテストケースを作るのはどう？

2021-05-28 03:33 UTC, arimakaoru commented on module/Pid.h
> +  double calculatePid(double targetValue, double presentValue);
目標値って、一度決めたら同じ値で何回も計算すると思うんだよね
メンバ変数にしてもいい気がするけど、どうかな？

2021-05-28 03:42 UTC, Hisataka-Hagiyama commented on module/Pid.h
> +  double calculatePid(double targetValue, double presentValue);
メンバ変数にしたほうが毎回目標値を指定する手間も省けるのでそのほうがいいと思います。
メンバ変数として修正をしておきます。

2021-05-28 10:47 UTC, Takahiro55555 commented on module/Pid.h
> +static const double DELTA = 0.01;  //周期[10ミリ秒]
グローバル変数にするくらいなら、他のクラスで周期の値を必要としない間はメンバ変数か、関数内に宣言してしまっても良い気がします。

2021-05-28 11:04 UTC, mutotaka0426 commented on module/Pid.h
> +static const double DELTA = 0.01;  //周期[10ミリ秒]
周期を使うクラスって動作系だけだから，グローバル変数にしてむやみにスコープを大きくしてしまうのもどうかと思いますね
動作制御をするクラスだけに使わせたいから，メンバ変数にしてインスタンス化するときに渡すでいいんじゃないでしょうか

2021-05-28 11:32 UTC, mutotaka0426 commented on test/PidTest.cpp
> +    EXPECT_DOUBLE_EQ(p + i + d, myPid.calculatePid(presentValue));
```suggestion
    double expected = p + i + d;
    EXPECT_DOUBLE_EQ(expected, myPid.calculatePid(presentValue));
```

上の方でやってるみたいに，アサーションではできるだけ`expected`を使って欲しい
あと，`expected`と比較する実際の値は`actual`にして欲しいかな（actualPidとかでもok）
ちゃんと言ってなかったわごめん！

2021-05-28 11:33 UTC, mutotaka0426 commented on test/PidTest.cpp
> +    EXPECT_DOUBLE_EQ(p + i + d, myPid.calculatePid(presentValue));
ここも

2021-05-28 11:40 UTC, mutotaka0426 commented on test/PidTest.cpp
> +    EXPECT_DOUBLE_EQ(0.612, myPidGain.kd);
```suggestion
    double expected_p = 0.1;
    double expected_i = 0.03;
    double expected_d = 0.612;
    PidGain actualPidGain(expected_p, expected_i, expected_d);
    EXPECT_DOUBLE_EQ(expected_p, actualPidGain.kp);
    EXPECT_DOUBLE_EQ(expected_i, actualPidGain.ki);
    EXPECT_DOUBLE_EQ(expected_d, actualPidGain.kd);

```
テストコードにおいてマジックナンバーは避けるべきなので，ちょっと面倒かもしれないけど変数に入れてからテストしてください
下の2つとかも

2021-05-31 10:19 UTC, Takahiro55555 commented on test/PidTest.cpp
> +    Pid actualPid(0.6, 0.02, 0.03, 70);
個人的には、以下のように書いたほうが分かりやすい(?)と思ったのですが、以下のように書かなかった理由などはあるのでしょうか？

現状のコードの書き方のほうが一般的とか？

```suggestion
    PidGain actualPidGain(expected_p, expected_i, expected_d);
```

2021-05-31 10:57 UTC, Hisataka-Hagiyama commented on test/PidTest.cpp
> +    Pid actualPid(0.6, 0.02, 0.03, 70);
意図してこの書き方をしたという訳ではありません。
確かに挙げられた書き方の方が簡潔だと思います。
修正しておきます。

2021-06-02 03:32 UTC, arimakaoru submitted a review, later dismissed
LGTM👍

2021-06-02 09:33 UTC, sugaken0528 commented on test/PidTest.cpp
> +
DELTAが0の時はテストしなくていいの?
dが0除算になっちゃう的な

2021-06-02 09:58 UTC, Hisataka-Hagiyama commented on test/PidTest.cpp
> +
0を渡したらinfになるので良くないとは思いますが、0の場合どうしたらいいですかね？デフォルトの周期で計算するのがいいですか？

2021-06-02 10:25 UTC, arimakaoru submitted a review, later dismissed

2021-06-02 10:29 UTC, Takahiro55555 submitted a review, later dismissed
LGTM!!!

2021-06-02 10:51 UTC, sugaken0528 approved these changes
遅くなってごめんね

2021-06-02 11:03 UTC, mutotaka0426 approved these changes
えるじーてぃーえむ

2021-06-02 11:58 UTC, kodama0720 submitted a review, later dismissed
LGTM

2021-06-02 13:01 UTC, miyashita64 submitted a review, later dismissed
LGTM!

2021-06-02 13:09 UTC, hiroto0927 submitted a review, later dismissed

2021-06-02 14:17 UTC, yutotanaka24 submitted a review, later dismissed

2021-06-03 05:48 UTC, Takahiro55555 approved these changes

2021-06-03 06:13 UTC, miyashita64 approved these changes

2021-06-03 06:13 UTC, arimakaoru approved these changes

2021-06-03 06:16 UTC, kodama0720 approved these changes

2021-06-03 06:16 UTC, hiroto0927 approved these changes

2021-06-03 06:20 UTC, etckanikama approved these changes

2021-06-03 06:20 UTC, merged