close #14 コース情報を保持する
KatLab-MiyazakiUniv/etrobocon2021 pull request #27
Opened 2021-05-27 09:37 UTC by hiroto0927

# チェックリスト
- [x] clang-formatしている
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている
# 変更点
- CourseInfo.cpp Range.cpp CourseInfo.h Range.hを追加した。
- Makefileを更新した。

2021-05-28 14:22 UTC, hiroto0927 commented on Makefile.inc
> +
Makefileのフォーマットを修正しました。
確認お願いします。

2021-05-28 14:48 UTC, mutotaka0426 reviewed
ちょっと例外処理についてはどうすればいいか難しいな
競技中にシステムが止まってしまうようなことは避けたいんだけど
エラー文を表示させるだけじゃダメかな？

2021-05-28 14:48 UTC, mutotaka0426 commented on module/CourseInfo.cpp
> +    std::cout << str;
例外処理を入れてくれてるのは良いと思うんだけど，これだと変な値が入ったまま次の処理に移っちゃうから，何か適当に値を入れ直しておいた方がいいかも？
エラー文はそのまま出してくれてていいよ

2021-05-28 14:48 UTC, mutotaka0426 commented on module/CourseInfo.cpp
> +    std::cout << str;
いや，そもそも組込みシステムに例外処理は使うべきではないのかも．．．
仮に競技中に例外処理に入ったらまずいかも
@arimakaoru @Takahiro55555 @sugaken0528 @etckanikama

2021-05-28 14:48 UTC, mutotaka0426 commented on module/CourseInfo.cpp
> +  return ranges[_id].getName();
ここも多分，変な値が入ったままだとセグフォでないかな

2021-05-29 03:31 UTC, hiroto0927 commented
Range.cppにて、Range.hでnameとdistanceをconstで定義しており、コンストラクタ内での変更ができないため、nameとdistanceに不適切な値が入力された際に、変更がきかないのですがどうすればよいですか？

他の例外処理は、値を入れて、エラー文を出力するように変更しました。

2021-05-29 04:03 UTC, mutotaka0426 commented
> Range.cppにて、Range.hでnameとdistanceをconstで定義しており、コンストラクタ内での変更ができないため、nameとdistanceに不適切な値が入力された際に、変更がきかないのですがどうすればよいですか？

constで定義した変数には代入演算子使えないんだよね
その場合は多分constexprにしてみたらできないかな

2021-05-29 04:12 UTC, mutotaka0426 commented
ごめん嘘
constexprはだめだわ

2021-05-29 05:05 UTC, mutotaka0426 commented
コンストラクタの初期化で三項演算子使えるみたいだから，
name(条件式?真の時の値:偽の時の値)みたいに定義できるよ

2021-05-29 12:34 UTC, hiroto0927 commented
三項演算子に変更して試してみます。

2021-05-31 04:27 UTC, arimakaoru requested changes
区間名っているかな？
これがなければ、かなりシンプルにできると思う。

2021-05-31 04:27 UTC, arimakaoru commented on module/Range.h
> +  const std::string name;
あったら便利そうだけど、実際に使うかな..…

2021-05-31 04:27 UTC, arimakaoru commented on module/CourseInfo.cpp
> +  if(_brightness < 0 || 256 <= _brightness) {
```suggestion
  if(_brightness < 0 || 100 < _brightness) {
```

実は、輝度の範囲は未定なので、とりあえずEV3 APIに合わせて0～100にしておこうか。

以下、未定の理由
EV3 APIにあるgetBrightness関数では、0～100が返される。
一方で、実機の場合はカラーセンサーにちょっと問題があって、今まではgetBrightness関数を使わずに、RGB値から輝度を計算して、0～255の範囲になるようにしていた。
今年は、以下の2点について検証・議論が必要です。
- シミュレータでもカラーセンサーの問題は起きるのか
- 問題が起きるとしても、輝度の範囲はAPIに合わせて0～100にした方が良いのではないか

2021-05-31 04:27 UTC, arimakaoru commented on module/CourseInfo.cpp
> +    brightness = 128;
```suggestion
    brightness = 50;
```

2021-05-31 04:27 UTC, arimakaoru commented on module/CourseInfo.h
> +  int getBrightness();
```suggestion
  int getTargetBrightness();
```

オプション (変えても変えなくてもどっちでもいい)
APIにカラーセンサーから輝度を取得するgetBrightness関数があるから、同じ名前だと紛らわしいかも？

2021-05-31 04:27 UTC, arimakaoru commented on module/CourseInfo.cpp
> +  return ranges[id].getDistance();
```suggestion
  // 名前が一致する区間を探索
  for(int i = 0; i < len; i++) {
    // 発見時はidの区間の距離を返す
    if(ranges[i].getName() == _name) {
      return ranges[id].getDistance();
    }
  }

  // 名前が一致する区間が見つからなかった場合、0を返す
  std::cout << "CourseInfo:該当する区間は存在しません。\n";
  return 0;
```

2021-05-31 10:27 UTC, Takahiro55555 commented on module/CourseInfo.h
> +  int getBrightness();
ついでに、メンバ変数も `brightness` から `targetBrightness` に変更してもよい気がします。

これも、オプションですが...

2021-05-31 10:34 UTC, Takahiro55555 commented on module/CourseInfo.cpp
> +  return ranges[id].getDistance();
@arimakaoru @sugaken0528 @mutotaka0426 

戻り値でエラーの有無が判定できるなら、呼び出し元でエラーメッセージを表示する（又は表示しない）かどうか決定出来たほうが良い気がするのですが、どうでしょうか？

2021-05-31 10:59 UTC, Takahiro55555 commented on module/CourseInfo.cpp
> +    std::cout << "CourseInfo:該当する区間は存在しません。\n";
@arimakaoru @sugaken0528 @mutotaka0426 

戻り値でエラーの有無が判定できるなら、呼び出し元でエラーメッセージを表示する（又は表示しない）か決定出来たほうが良い気がするのですが、どうでしょうか？

2021-05-31 10:59 UTC, Takahiro55555 commented on module/CourseInfo.cpp
> + *@author higuchi/miyashita
他の人のフォーマットと整合性を持たせるなら、`*`と`@`の間にスペースを入れたほうが良い気がします。
あと、ユーザ名の区切り文字も。

```suggestion
 * @file CourseInfo.cpp
 * @brief コース情報
 * @author higuchi,miyashita

```

@arimakaoru @shigyo123 @mutotaka0426 
流石に、この部分は各自で好きなように書く方針のほうが良いですか？

(個人的には、ユーザ名の区切り文字の後にスペースを１つ入れるようにしたい...)

2021-06-01 01:52 UTC, arimakaoru commented on module/CourseInfo.cpp
> +  if(_brightness < 0 || 100 <= _brightness) {
```suggestion
  if(_brightness < 0 || 100 < _brightness) {
```

2021-06-01 01:52 UTC, arimakaoru commented on module/CourseInfo.cpp
> + *@author higuchi/miyashita
まあ、揃ってると綺麗だよね

2021-06-01 02:00 UTC, arimakaoru reviewed
だいたい良さそう！

2021-06-01 02:58 UTC, mutotaka0426 commented on module/CourseInfo.cpp
> +  if(_brightness < 0 || 100 <= _brightness) {
こういうミスがあるから境界値テストはした方がよさそうですね
0と-1と100と101を渡した時のテストはやろうか

2021-06-01 03:54 UTC, hiroto0927 commented on module/CourseInfo.cpp
> +  if(_brightness < 0 || 100 <= _brightness) {
境界値テストの方を変更しました。
確認お願いします。

2021-06-01 05:26 UTC, Hisataka-Hagiyama requested changes

2021-06-01 05:26 UTC, Hisataka-Hagiyama commented on test/CourseInfo_test.cpp
> +    int expected = 0;
```suggestion
    CourseInfo info(100);
    int expected = 100;
```
輝度0を返す処理と同じことが書いてあるので、輝度100を返す処理に書き換えたほうがいいと思います

2021-06-01 17:01 UTC, hiroto0927 commented
シングルトンの導入をしましたが、目標輝度に入力値を入れる方法や距離の配列の扱い方が正しいかわかりません。
また、初期化の関係によりgetTagetBrightnessのテストが一括では通らない為、コメントアウトしています。
一つずつテストを試した場合は通りました。

2021-06-02 12:19 UTC, sugaken0528 approved these changes

2021-06-02 12:20 UTC, Takahiro55555 approved these changes

2021-06-02 12:21 UTC, arimakaoru approved these changes
LGTM!!

2021-06-02 12:24 UTC, hiroto0927 commented on module/CourseInfo.cpp
> +                                     Range("ST_4", 10.0f) }
区間名は現状使うことがないとの判断になっているので削除しています。
今、挙げているファイルでは配列に距離のみを保持させています。

2021-06-02 12:43 UTC, kodama0720 approved these changes

2021-06-02 12:43 UTC, kodama0720 commented on test/CourseInfo_test.cpp
> +    EXPECT_EQ(expected, info.getCourseDistances()[id]);
配列の中身を返す関数って"関数名()[id]"で呼び出すものなんですか？
個人的には"関数名(id)"で呼び出せた方が分かりやすいかと思いました。

2021-06-02 13:04 UTC, hiroto0927 commented on test/CourseInfo_test.cpp
> +    EXPECT_EQ(expected, info.getCourseDistances()[id]);
配列の中身一つ一つではなく、配列の中身を全て呼びだせば他で使うときメモリの節約？になると思いgetCourseDistance()関数は配列ごと取ってくるように作成しました。その為、今回はこのような形になっています。

2021-06-02 13:07 UTC, kodama0720 commented on test/CourseInfo_test.cpp
> +    EXPECT_EQ(expected, info.getCourseDistances()[id]);
なるほど、わかりました
良いと思います

2021-06-02 13:08 UTC, Hisataka-Hagiyama approved these changes
![LGTM](https://user-images.githubusercontent.com/66076307/120485433-0bf2e580-c3ef-11eb-80f7-eb431c96b326.jpg)

2021-06-02 13:15 UTC, mutotaka0426 approved these changes
えるじーてぃーえむ

2021-06-03 06:35 UTC, merged