close #16  計測する
KatLab-MiyazakiUniv/etrobocon2021 pull request #28
Opened 2021-05-29 07:58 UTC by kodama0720

# チェックリスト
- [ ] clang-formatしている
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている
# 変更点
- module/api下にMeasurer.cppとMeasurer.hを追加
- test/dummy下にMeasurer.cppとMeasurer.hを追加
- Makefileを更新

2021-05-31 04:47 UTC, arimakaoru requested changes
OK!
今思いついたけど、Measurerのdummyではなくてev3_api.hのdummyにしてもよかったね

2021-05-31 04:47 UTC, arimakaoru commented on Makefile.inc
> +    WController.o \
```suggestion
```
制御するのプルリクで追加してるよね？

2021-05-31 11:08 UTC, Takahiro55555 submitted a review, later dismissed
LGTM!!!

2021-06-01 05:19 UTC, Hisataka-Hagiyama requested changes

2021-06-01 05:19 UTC, Hisataka-Hagiyama commented on test/dummy/ev3api_motor.h
> + * \brief モータポートを表す番号
```suggestion
 * @brief モータポートを表す番号
```
コメントの書き方を統一した方がいいかなと思います

2021-06-01 05:19 UTC, Hisataka-Hagiyama commented on test/dummy/ev3api_motor.h
> + * \brief サポートするモータタイプ
```suggestion
 * @brief サポートするモータタイプ
```
ここも統一した方がいいかなと思います

2021-06-02 03:40 UTC, arimakaoru approved these changes
LGTM👍
dummyまでありがとう！！

2021-06-02 03:43 UTC, sugaken0528 approved these changes
good job

2021-06-02 10:30 UTC, Takahiro55555 approved these changes

2021-06-02 10:32 UTC, Hisataka-Hagiyama approved these changes
LGTM

2021-06-02 11:04 UTC, mutotaka0426 approved these changes
lgtm

2021-06-02 13:01 UTC, uchyam approved these changes
LGTM

2021-06-02 13:05 UTC, hiroto0927 approved these changes

2021-06-02 13:21 UTC, merged