制御する追加
KatLab-MiyazakiUniv/etrobocon2021 pull request #31
Opened 2021-05-30 16:08 UTC by yutotanaka24

# チェックリスト
- [x] clang-formatしている
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている
# 変更点
- module/api下にMeasurer.cppとMeasurer.hを追加
- test/dummy下にMeasurer.cppとMeasurer.hを追加
- Makefileを更新

2021-05-31 05:02 UTC, arimakaoru requested changes
だいたいOK！
あとは細かいところを！

2021-05-31 05:02 UTC, arimakaoru commented on test/dummy/Controller.h
> +#endif
dummyは今度きれいにしよう

2021-05-31 05:53 UTC, yutotanaka24 commented on module/api/Controller.h
> +  int suppressPwmValue(const int value);
limitの方が分かりやすそうですね。
そっちにしようと思います。

2021-05-31 09:30 UTC, sugaken0528 reviewed
制御クラスについては特に問題ないと思います👍
dummyって何だっけ?

2021-05-31 11:17 UTC, Takahiro55555 requested changes
@arimakaoru の指摘していた、`test/dummy/Controller.cpp`ファイルのタイプミスを修正すればOKだと思います。

2021-06-01 01:21 UTC, arimakaoru requested changes
dummy以外はOKです！
dummyの方は、 @kodama0720 が作ってくれてるので、あとの作業はこんな感じでどう？

1. 児玉君のプルリクをマージ 
2. 田中君がpullで児玉君の分を取り込む
3. testが通るか確認
4. 田中君の分を再push
5. 田中君の分をマージ

2021-06-01 01:31 UTC, arimakaoru commented
> 制御クラスについては特に問題ないと思います👍
> dummyって何だっけ?

問題
グーグルテストの実行時は、シミュレータを動かせないのでev3_api.hをincludeできない。そのため、ev3_api.hをincludeしているControllerクラスとかはテスト時にコンパイルエラーになる。

対策
本物のev3_api.hを模したダミーのev3_api.hを作って、テストのときはそれを使うようにする。

効果
ev3_api.hをincludeしているContorollerクラスとかもテスト時に使える。
つまり、Contorollerクラスを使う別のクラス (今後作るLineTracerクラスとか) もテストできるようになる。

2021-06-02 11:05 UTC, mutotaka0426 commented
プルリクメッセージ修正よろ

2021-06-02 20:36 UTC, hiroto0927 approved these changes

2021-06-03 14:07 UTC, arimakaoru approved these changes
LGTM!

2021-06-04 03:40 UTC, mutotaka0426 approved these changes
もう忘れてるだろうから俺がやったけど，プルリクのメッセージは間違ってるの気づいたらすぐに直してな
数秒で修正できるから

2021-06-04 03:45 UTC, miyashita64 approved these changes

2021-06-04 03:56 UTC, Hisataka-Hagiyama approved these changes
LGTM

2021-06-04 06:35 UTC, Takahiro55555 approved these changes

2021-06-04 06:36 UTC, merged