Mileageクラスのビルドが通るように修正
KatLab-MiyazakiUniv/etrobocon2021 pull request #39
Opened 2021-06-03 12:00 UTC by mutotaka0426

# チェックリスト
- [x] clang-formatしている
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている
# 変更点
- シングルトンクラスではなく静的クラスに変更した
- 定数の名前をコーディング規約に準じたものに変更した
- 定数をコンストラクタではなく，スコープで

2021-06-03 14:11 UTC, arimakaoru commented
テスト失敗してる

2021-06-03 17:42 UTC, mutotaka0426 commented
> テスト失敗してる

反省して欲しいですね

2021-06-03 17:46 UTC, mutotaka0426 commented
因みに今の状態だとmake通りません
CourseInfoを除外したらmake通る状態です

2021-06-04 00:28 UTC, arimakaoru requested changes
落ち着いて

2021-06-04 00:28 UTC, arimakaoru commented on module/Mileage.h
> +  // static constexpr double radius = 45;  //タイヤの半径[mm]
```suggestion
```
いらない

2021-06-04 00:28 UTC, arimakaoru commented on module/Mileage.h
> +  static const double RADIUS;
変数→関数の順に書く

2021-06-04 00:28 UTC, arimakaoru commented on module/Mileage.cpp
> +  // constexpr double RADIUS = 45.0;
いらない

2021-06-04 00:28 UTC, arimakaoru commented on module/Mileage.cpp
> +const double Mileage::RADIUS = 45.0;
.hで初期化したらダメなの？

2021-06-04 01:45 UTC, mutotaka0426 commented on module/Mileage.cpp
> +const double Mileage::RADIUS = 45.0;
static constのメンバ変数に代入する場合ヘッダーのほうに書くと通らないです
理由はちょっと理解できなかったです

2021-06-04 01:55 UTC, mutotaka0426 commented on module/Mileage.h
> +  static const double RADIUS;
なんでみんなapproveしたんでしょうね！！！！！！！！！！！！！！！！

直します

2021-06-04 03:49 UTC, miyashita64 approved these changes

2021-06-04 03:52 UTC, arimakaoru approved these changes
![LGTM](https://image.lgtmoon.dev/129056)

2021-06-04 04:06 UTC, Hisataka-Hagiyama approved these changes
担当のチケットで修正を生んでしまい申し訳ありません（特にコーディング規約に反したミス）。修正ありがとうございます。

2021-06-04 04:17 UTC, arimakaoru commented
> 担当のチケットで修正を生んでしまい申し訳ありません（特にコーディング規約に反したミス）。修正ありがとうございます。

レビューで誰も気づかなかったからね～
マージした後に気づいたミスはチームの責任

2021-06-04 04:57 UTC, kodama0720 approved these changes

2021-06-04 06:42 UTC, Takahiro55555 approved these changes

2021-06-06 12:36 UTC, hiroto0927 approved these changes

2021-06-07 02:27 UTC, merged