Ticket 35
KatLab-MiyazakiUniv/etrobocon2021 pull request #50
Opened 2021-06-10 06:32 UTC by Hisataka-Hagiyama

# チェックリスト
- [ ] clang-formatしている
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている
# 変更点
- XXXを変更した

2021-06-10 07:46 UTC, uchyam commented on module/EtRobocon2021.cpp
> +    tslp_tsk(10);
controllerクラスで呼び出す

2021-06-10 07:46 UTC, sugaken0528 commented on module/LineTraceArea.h
> +
bool型に変更

2021-06-10 07:55 UTC, Hisataka-Hagiyama commented on module/LineTraceArea.h
> +static const int ARRAYSIZE = 7;
左右で配列のサイズを変えられるようにし、名前をわかりやすいものにする

2021-06-10 07:58 UTC, Hisataka-Hagiyama commented on module/LineTraceArea.h
> +  static const std::array<SectionParam, ARRAYSIZE> leftCourseInfo;   //左コースの情報
定数は大文字にする

2021-06-10 08:00 UTC, Hisataka-Hagiyama commented on module/LineTraceArea.h
> +#endif
_EDGEをbool型にする

2021-06-13 04:56 UTC, Hisataka-Hagiyama commented
LineTracerクラスがMergeされていないので、ビルドとEtrobocon2021のテストは通っていません。
マージ後、gtestとライントレースエリアを走行できるかのテストを行う予定です。

2021-06-14 05:20 UTC, mutotaka0426 requested changes
コース距離の修正だけで他は大丈夫そう
後はLineTracerクラスがマージされたら，pullして最新の状態にしてから再プッシュして下さい

2021-06-14 05:20 UTC, mutotaka0426 commented on module/LineTraceArea.cpp
> +        SectionParam{ 802.254, 50, 100, PidGain(0, 0, 0) } };
```suggestion
        SectionParam{ 807.404, 50, 100, PidGain(0, 0, 0) } };
```
ここも

2021-06-14 05:20 UTC, mutotaka0426 commented on module/LineTraceArea.cpp
> +    = { SectionParam{ 1629.980, 50, 100, PidGain(0, 0, 0) },
```suggestion
    = { SectionParam{ 1625.340, 50, 100, PidGain(0, 0, 0) },
```

2021-06-14 05:20 UTC, mutotaka0426 commented on module/LineTraceArea.cpp
> +        SectionParam{ 802.254, 50, 100, PidGain(0, 0, 0) } };
```suggestion
        SectionParam{ 807.404, 50, 100, PidGain(0, 0, 0) } };
```

2021-06-14 15:16 UTC, miyashita64 commented on module/LineTraceArea.cpp
> +
arrayサイズに与える固定値が逆だと思います。
Lコースが"RIGHT"SECTIONSIZE、Rコースが"LEFT"SECTIONSIZEになっています。

2021-06-14 15:19 UTC, miyashita64 commented on module/LineTraceArea.cpp
> +const std::array<SectionParam, LineTraceArea::RIGHTSECTIONSIZE> LineTraceArea::LEFTCOURSEINFO
arrayサイズに与える固定値が逆だと思います。
Lコースが"RIGHT"SECTIONSIZE、Rコースが"LEFT"SECTIONSIZEになっています。

2021-06-15 02:05 UTC, arimakaoru reviewed
今のところは良さそう！

2021-06-15 02:36 UTC, arimakaoru requested changes

2021-06-15 02:36 UTC, arimakaoru commented on module/LineTraceArea.cpp
> +  LineTracer linetracer(IS_LEFT);
LineTracerクラスのコンストラクタでは、bool型のエッジを渡すようにする。
（kodama, tanakaペアと要相談）

2021-06-15 03:12 UTC, Hisataka-Hagiyama commented on module/LineTraceArea.cpp
> +  LineTracer linetracer(IS_LEFT);
```
void LineTraceArea::runLineTraceArea()
{
  const SectionParam* param;
  bool edge;  // LRのエッジ

  if(IS_LEFT) {
    // Lコースの場合
    param = LEFT_COURSE_INFO.begin();
    edge = true;
  } else {
    // Rコースの場合
    param = RIGHT_COURSE_INFO.begin();
    edge = false;
  }

  // LineTracerにエッジを与えてインスタンス化する
  LineTracer lineTracer(edge);

  // LRに応じて各区間を順番に走らせる
  for(int section = 0; section < (IS_LEFT ? LEFT_SECTION_SIZE : RIGHT_SECTION_SIZE); section++) {
    // Linetracerクラスのrun関数に区間の情報を渡して走行させる
    lineTracer.run(param[section].sectionDistance, param[section].sectionTargetBrightness,
                   param[section].sectionPWM, param[section].sectionPidGain);
  }
}
```
このようにすれば大丈夫でしょうか？
@kodama0720 @yutotanaka24

2021-06-15 09:47 UTC, Takahiro55555 requested changes
コメントした箇所の確認をお願いします。

2021-06-15 09:47 UTC, Takahiro55555 commented on module/EtRobocon2021.cpp
>   */
コミット履歴を見てみたら、昨年のファイルをコピーしたときに自分が消し忘れたコメントのようです...
プログラムの機能とコメントの内容に齟齬がある場合、修正してもらえると助かります🙇‍♂️

2021-06-15 09:47 UTC, Takahiro55555 commented on module/LineTraceArea.cpp
> +  }
好みの問題なので、修正するかどうかは任せます...

個人的には、
```suggestion
  if(IS_LEFT_COURSE) {
    param = LEFT_COURSE_INFO.begin();
  } else {
    param = RIGHT_COURSE_INFO.begin();
  }
  isLeftEdge = !IS_LEFT_COURSE;
```
のほうが直感的?な気がして好きです。

2021-06-15 09:47 UTC, Takahiro55555 commented on module/LineTraceArea.cpp
> +  for(int section = 0; section < (IS_LEFT ? LEFT_SECTION_SIZE : RIGHT_SECTION_SIZE); section++) {
もしかして、こう？
```suggestion
  for(int section = 0; section < (IS_LEFT_COURSE ? LEFT_SECTION_SIZE : RIGHT_SECTION_SIZE); section++) {
```

2021-06-15 17:05 UTC, sugaken0528 commented on module/LineTraceArea.h
> +  int sectionPWM;               //区間のPWM値
ここも

2021-06-15 17:05 UTC, sugaken0528 commented on module/LineTraceArea.cpp
> +                   param[section].sectionPWM, param[section].sectionPidGain);
PWMって略語だけどキャメルケースとしてはPwmにした方がいいんやない?
規約違反にはならんとは思うけどPIDもPidになってるし。

2021-06-15 18:47 UTC, sugaken0528 commented on module/LineTraceArea.cpp
> +  }
Lコースだったら右エッジでRコースだったら左エッジって絶対だっけ？
そうじゃないなら今のままでも良さそう

2021-06-16 03:54 UTC, mutotaka0426 commented on module/LineTraceArea.cpp
> +  }
ライントレースエリアではエッジは必ずコースの逆になるんじゃない？
だから上田君の言ってる反転させる代入文の方が個人的にはいいと思うけど，これはこれで理解はしやすいのかもしれないから好みの問題だね

2021-06-16 09:48 UTC, Takahiro55555 approved these changes
![LGTM](https://image.lgtmoon.dev/130492)

2021-06-16 09:58 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/125345)

2021-06-16 10:02 UTC, sugaken0528 approved these changes
![LGTM](https://image.lgtmoon.dev/130489)

2021-06-16 10:21 UTC, arimakaoru approved these changes
OK🎉

2021-06-16 10:39 UTC, miyashita64 approved these changes
LGTM

2021-06-16 10:40 UTC, hiroto0927 approved these changes

2021-06-16 10:41 UTC, merged