ライントレーサークラス追加
KatLab-MiyazakiUniv/etrobocon2021 pull request #51
Opened 2021-06-10 06:47 UTC by yutotanaka24

# チェックリスト
- [ ] clang-formatしている
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている
# 変更点
- XXXを変更した

2021-06-10 07:04 UTC, mutotaka0426 commented on module/LineTracer.h
> +  Mileage mileage;
Mileageは静的クラスなのでインスタンスは不要

2021-06-10 07:27 UTC, Takahiro55555 commented on module/LineTracer.h
> +  LineTracer(int _edge);
`_edge`を`is_left`のようなBool型にする

2021-06-10 07:27 UTC, Takahiro55555 commented on module/LineTracer.cpp
> +  }
ループの最後に EV3 API の sleep 関数を呼び出すようにする

2021-06-10 07:27 UTC, Takahiro55555 commented on module/LineTracer.cpp
> +LineTracer::LineTracer(int _edge) : edge(_edge) {}
メンバ変数は全てコンストラクタで初期化するようにする

2021-06-10 07:27 UTC, Takahiro55555 commented on module/LineTracer.cpp
> +
`LineTracer::run`関数の先頭で、`motorCount`をリセットするようにする。

`currentDistance`をメンバ変数から外す

2021-06-10 07:27 UTC, Takahiro55555 commented on module/LineTracer.h
> +  double currentPid;
`run`関数の中でしか使用していないため、`currentPid`をメンバ変数から除外する

2021-06-10 07:37 UTC, Takahiro55555 reviewed
テストファイルは削除する

2021-06-10 13:36 UTC, arimakaoru commented
距離に負の値を指定した場合は、どんな動作になるんだろう
後ろに進みながらライントレースする？

2021-06-12 09:14 UTC, kodama0720 commented on module/LineTracer.cpp
> +}
controller.reset();で走行距離がリセットされていないようなのですが、原因がわかりません。一応、去年のソースコードを参考に以下のように書き換えたら動くことは確認できましたが、できればAPIの関数を使いたいです。どうすればよいでしょうか。
```suggestion
void LineTracer::run(double targetDistance, int targetBrightness, int pwm, const PidGain& gain)
{
  int initialDistance = Mileage::calculateMileage(measurer.getRightCount(), measurer.getLeftCount());
  int currentDistance = initialDistance;  // 現在の走行距離
  double currentPid = 0;
  Pid pid(gain.kp, gain.ki, gain.kd, targetBrightness);

  //走行距離が目標距離を超えるまで繰り返す
  while(true) {
    currentDistance = Mileage::calculateMileage(measurer.getRightCount(), measurer.getLeftCount());
    if(currentDistance - initialDistance > targetDistance) {
      break;
    }
    // PID計算
    currentPid = pid.calculatePid(measurer.getBrightness()) * edge;
    //モータのPWM値をセット
    controller.setRightMotorPwm(pwm - currentPid);
    controller.setLeftMotorPwm(pwm + currentPid);
    currentDistance = Mileage::calculateMileage(measurer.getRightCount(), measurer.getLeftCount());
    // 10ミリ秒待機
    controller.sleep();
  }
}
```

2021-06-12 12:46 UTC, arimakaoru commented on module/LineTracer.cpp
> +}
reset前後で、getCountで返ってくる値が変わらないってこと？

2021-06-12 13:29 UTC, mutotaka0426 commented on module/LineTracer.cpp
> +}
多分だけど，Controllerクラスのreset関数が問題なんじゃないかな
去年（と確か一昨年も）同じような問題があったんだけど，タスク周期の問題？でリセットしきれないから，下のコードみたいにして両輪のカウントが0になるまでwhile文回してたんだよね
これでできないか確認してみて
```
void Controller::resetMotorCount(){
  while((this->getLeftMotorCount() != 0) || (this->getRightMotorCount() != 0)) {
    leftWheel.reset();
    rightWheel.reset();
    this->tslpTsk(20000);
  }
}
```

2021-06-12 13:37 UTC, mutotaka0426 commented on module/Controller.h
> +  void reset();
コーディング規約にもあるように関数名は動詞+名詞の形が好ましくて，名詞は省略してもいいんだけど，今回はモータカウントをリセットするって意味の関数だからresetMotorCountとかのほうがいいんじゃないかな
リセットするものってモータ以外にも今後出てくるかもしれないし

2021-06-12 14:14 UTC, mutotaka0426 requested changes
微細な修正は入れたけど，全体的には結構いい感じだと思う

2021-06-12 14:14 UTC, mutotaka0426 commented on module/Controller.h
>  using namespace ev3api;
ヘッダファイルにusing宣言を書き込むのは，グローバルが汚染されて良くないね
例えば，ev3apiの名前空間で定義されている関数名と，ユーザが定義した関数名等が被ってしまった場合，名前の衝突が起きて予期せぬバグが発生しかねないんだよね
特にContorollerクラスなんかはいろんなクラスがincludeするから影響も大きいし，面倒かもしれないけどヘッダファイルではusingは使わないようにお願いします

ていうか，最初にControllerクラスのプルリクを出されたときに指摘するべきだったわ
よろしく

2021-06-14 04:28 UTC, arimakaoru requested changes
指摘事項は @mutotaka0426 と同じ箇所だけです。

シミュレータを使ったテストでは、「指定した距離だけライントレースする」処理を作ってもらったので、「実際に走らせてみると、どれくらい正確に指定した距離だけライントレースできるか」を示してほしい。
「数字で示すこと」と「複数の側面から示すこと」ができると、より説得力を持たせられると思う。

（実験の例）
実験内容：LineTracer::run関数にXmmを指定して実行し、実際に走行した距離を測定する。（実験内容を明らかにすることで、実験の公平性を示す）
試行回数：10回（多ければ多い程よいけど...）
実験結果：表で10回分の結果を示す。平均誤差率を計算する。（数字で示す）
さらに、Xmmの値を変えて、別のパターンもやってみると、より説得力が増す。（複数の側面から示す）

2021-06-14 04:28 UTC, arimakaoru commented on module/LineTracer.cpp
> +}
動画では、どのコードで走らせているの？
プルリクで出されているコード？それとも、児玉君が書いてるコード？

2021-06-14 05:04 UTC, Hisataka-Hagiyama commented on module/LineTracer.cpp
> +void LineTracer::run(double targetDistance, int targetBrightness, int pwm, PidGain& gain)
```suggestion
void LineTracer::run(double targetDistance, int targetBrightness, int pwm, const PidGain& gain)
```
僕がこの関数を呼び出す際に、constな構造体のメンバ変数を実引数に渡すので、参照型の仮引数にはconstをつけておかないとエラーが出たりする気がします。言い忘れてて申し訳ないです。

2021-06-14 05:04 UTC, Hisataka-Hagiyama commented on module/LineTracer.h
> +  void run(double targetDistance, int targetBrightness, int pwm, PidGain& gain);
```suggestion
  void run(double targetDistance, int targetBrightness, int pwm, const PidGain& gain);
```
同じく参照型の引数にconstをつけたほうがいいと思います。

2021-06-14 05:38 UTC, kodama0720 commented on module/LineTracer.cpp
> +}
プルリクのコードでrun関数の呼び出し1回で走らせています。

2021-06-14 14:46 UTC, Hisataka-Hagiyama commented on module/EtRobocon2021.cpp
> +  lineTracer.run(807.404, 20, 30, PidGain(0.8, 0.01, 0.01));
この部分は「ライントレースエリアを攻略する」のチケットで実装する部分なので必要ないと思います。

2021-06-14 14:48 UTC, Hisataka-Hagiyama commented on module/EtRobocon2021.cpp
> +#include "LineTracer.h"
ヘッダファイルも必要ないと思います。

2021-06-14 16:49 UTC, mutotaka0426 commented on module/EtRobocon2021.cpp
> +  lineTracer.run(807.404, 20, 30, PidGain(0.8, 0.01, 0.01));
萩山君が言ってるように，動作のテストのために使用したコードはpushしないでいいよ

2021-06-15 03:30 UTC, arimakaoru requested changes
エッジのところは変えたほうが良いかな

2021-06-15 09:10 UTC, Takahiro55555 requested changes
コメントした箇所以外は大丈夫だと思います。

2021-06-16 04:01 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/34979)

2021-06-16 04:06 UTC, arimakaoru approved these changes
![LGTM](https://image.lgtmoon.dev/130387)

2021-06-16 05:19 UTC, Hisataka-Hagiyama approved these changes
![LGTM](https://user-images.githubusercontent.com/66076307/122162080-db5e8180-cead-11eb-9e97-19dc1068c596.jpg)

2021-06-16 06:15 UTC, sugaken0528 approved these changes
![LGTM](https://image.lgtmoon.dev/130432)

2021-06-16 06:16 UTC, mutotaka0426 requested changes
よろしく！！！

2021-06-16 06:16 UTC, mutotaka0426 commented on module/Controller.cpp
> +}
```suggestion
void Controller::sleep(int milliSec)
{
  clock.sleep(milliSec);
}
```
変数名はキャメルケースでよろしく

2021-06-16 06:16 UTC, mutotaka0426 commented on module/Controller.h
> +  void sleep(int milli_sec = 10);
```suggestion
   * @param milliSec スリープ時間(ミリ秒)
   */
  void sleep(int milliSec = 10);
```
ここも

2021-06-16 09:48 UTC, mutotaka0426 approved these changes

2021-06-16 09:50 UTC, Takahiro55555 approved these changes
![LGTM](https://image.lgtmoon.dev/130492)

2021-06-16 09:52 UTC, uchyam approved these changes

2021-06-16 10:00 UTC, merged