closed #56 色を取得・識別する
KatLab-MiyazakiUniv/etrobocon2021 pull request #68
Opened 2021-06-19 09:45 UTC by miyashita64

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
- Measurerクラスに、getColorId()を追加
- ColorJudge.h, ColorJudge.cpp を作成
- MeasurerTest.cpp, ColorJudgeTest.cpp を作成
- ColorSensorクラスに色識別に関するダミーを追加

# 動作テスト

## 実験方法
- LineTrace.cpp run関数のループ内に、色識別番号と、白もしくは黒かの判定結果を表示する
- 色識別番号
  COLOR_NONE = 0,
  COLOR_BLACK = 1,
  COLOR_BLUE = 2,
  COLOR_GREEN = 3,
  COLOR_YELLOW = 4,
  COLOR_RED = 5,
  COLOR_WHITE = 6,
  COLOR_BROWN = 7,
  TNUM_COLOR  // サイズ

## 実験結果
- 白(6)→緑(3)→白(6) を認識していることを確認

## 添付資料
- 後ほど、動画を編集でき次第掲載

2021-06-19 09:50 UTC, hiroto0927 commented
https://user-images.githubusercontent.com/83230897/122638438-09062d80-d12f-11eb-8c40-29abc47738b2.mp4

2021-06-19 10:41 UTC, arimakaoru requested changes
ちゃんと言ってなくてごめん！

2021-06-19 10:41 UTC, arimakaoru commented on module/Measurer.cpp
> +  return static_cast<COLOR_NUMBER>(colorSensor.getColorNumber());
ごめん！
getColorNumber関数は、シミュレータでは非推奨！

https://github.com/ETrobocon/etrobo/wiki/api_ev3rt_on_athrill#c-api-5

2021-06-19 10:45 UTC, miyashita64 commented on module/Measurer.cpp
> +  return static_cast<COLOR_NUMBER>(colorSensor.getColorNumber());
そうなんですね…
rgbから計算します。

ありがとうございます！

2021-06-20 15:03 UTC, sugaken0528 reviewed
早めのプルリク素晴らしい
RGB変換処理ができたらまた見にくるね♡

2021-06-20 15:09 UTC, sugaken0528 commented on test/ColorJudgeTest.cpp
> +}  // namespace etrobocon2021_test
TNUM_COLOR(サイズ)がこのテストのためにあるのだとしたら何かいらない気がするぞ🤔

isBlackWhite関数はCOLOR_NUMBER型を入力として受け取るから、テストするならCOLOR_NUMBER型の最大値のTNUM_COLORをテスト(上記のテスト)すれば良いんかってなったけど、それならTNUM_COLORがそもそもいらなくてCOLOR_BROWNをテストすれば良いんじゃね?ってなった次第でございます。
ま要するにTNUM_COLORの存在意義が分からないだけ。

誰か意見ください。

2021-06-20 17:15 UTC, miyashita64 commented on test/ColorJudgeTest.cpp
> +}  // namespace etrobocon2021_test
APIのgetColorNumer()が返す、enum型のcolorid_t にTNUM_COLERがあったので、同じ構成にしていました。
今のところ使う場所がないので、削除しておこうと思います。

2021-06-20 17:19 UTC, sugaken0528 commented on test/ColorJudgeTest.cpp
> +}  // namespace etrobocon2021_test
なるほどね!

2021-06-21 01:52 UTC, arimakaoru reviewed
こうしたらどうかな？
@Takahiro55555 @sugaken0528 @mutotaka0426 も見て〜

## Measurerクラス
- getRawColor関数を追加
  - 引数なし、戻り値rgb_raw_t型 （EV3APIのgetRawColor関数は、引数rgb_raw_t型で戻り値なしだけど、どっちがいいかな...）

## ColorJudgeクラス
- COLOR_NUMBERをenum classで定義
- getColor関数を追加
  - 引数rgb_raw_tの参照型、戻り値COLOR_NUMBER型

2021-06-21 01:52 UTC, arimakaoru commented on module/Measurer.h
> +  COLOR_NUMBER getColorId();
`getColorNumber()`ではなくて、`getColorId()`なのは、なにか理由があるの？

2021-06-21 01:52 UTC, arimakaoru commented on module/ColorJudge.cpp
> +  return (colorNumber == COLOR_NUMBER::COLOR_BLACK || colorNumber == COLOR_NUMBER::COLOR_WHITE);
関数に分ける程の処理ではない気がするな...

2021-06-21 02:00 UTC, hiroto0927 commented on module/Measurer.h
> +  COLOR_NUMBER getColorId();
getColorNumber()にしなかったのは、APIのgetColorNumber()関数と関数名が被るため、getColorId()にしました。

2021-06-21 02:09 UTC, arimakaoru commented on module/Measurer.h
> +  COLOR_NUMBER getColorId();
なるほど！
MeasurerクラスとControllerクラスは、APIの[ラッパークラス](https://e-words.jp/w/%E3%83%A9%E3%83%83%E3%83%91%E3%83%BC%E3%82%AF%E3%83%A9%E3%82%B9.html)だから、関数名は被ってもいいよ！（getBrightness関数は被ってる）

まあ、わかりやすい方でいいよ

2021-06-21 04:14 UTC, mutotaka0426 commented on module/ColorJudge.cpp
> +  return (colorNumber == COLOR_NUMBER::COLOR_BLACK || colorNumber == COLOR_NUMBER::COLOR_WHITE);
白黒判定は呼び出す側がしていい気がしますね

2021-06-21 04:21 UTC, mutotaka0426 commented on module/Measurer.h
> +  COLOR_NUMBER getColorId();
> ## Measurerクラス
> * getRawColor関数を追加
>   
>   * 引数なし、戻り値rgb_raw_t型 （EV3APIのgetRawColor関数は、引数rgb_raw_t型で戻り値なしだけど、どっちがいいかな...）
> 
> ## ColorJudgeクラス
> * COLOR_NUMBERをenum classで定義
> * getColor関数を追加
>   
>   * 引数rgb_raw_tの参照型、戻り値COLOR_NUMBER型

補足しておくと，ColorJadgeクラスでは引数で受け取ったrgb値が何の色を示しているのか計算する処理を書いてほしい
あと，COLOR_NUMBER型は，rgb値からウチ独自の変換をしたものにしてほしいから，ColorJadge.hをincludeしたファイルだけが使えるようにしたい．だからenumはColorJadgeに書いてほしい

2021-06-21 05:33 UTC, mutotaka0426 requested changes

2021-06-24 03:24 UTC, arimakaoru reviewed
だいたいOK!
各色ごとに、色識別の精度を計測してほしいな

2021-06-24 03:24 UTC, arimakaoru commented on module/Measurer.cpp
> +  rgb_raw_t& rgbRef = rgb;
これって必要？

2021-06-24 03:24 UTC, arimakaoru commented on module/ColorJudge.h
> +  COLOR_WHITE = 6,
NONE, BLACK, BLUE, ... みたいに色の名前だけでよくない？
`COLOR_NUMBER::COLOR_BLACK` って書くから、そんなにCOLORCOLOR書かなくても良さそう。
もはや、`COLOR::BLACK`でよくない？

2021-06-24 03:24 UTC, arimakaoru commented on module/ColorJudge.h
> +  static const int VALUE_BORDER = 128;      // 白か黒かの明度の境界
これってどうやって決めたの？

2021-06-24 03:24 UTC, arimakaoru commented on module/ColorJudge.cpp
> +  int min = (rgb.r < rgb.g && rgb.r < rgb.b) ? rgb.r : (rgb.g < rgb.b) ? rgb.g : rgb.b;
Clever!

2021-06-24 03:24 UTC, arimakaoru commented on module/ColorJudge.cpp
> +COLOR_NUMBER ColorJudge::getColorNumber(rgb_raw_t& rgb)
```suggestion
COLOR_NUMBER ColorJudge::getColorNumber(rgb_raw_t const& rgb)
```

参照渡しだと、値の書き換えが可能になってしまう。
書き換える必要がない場合は、constを付けて書き換えを不可にすることで、呼び出し側は安心して呼び出せる。
...らしい。
https://qiita.com/agate-pris/items/05948b7d33f3e88b8967

2021-06-28 03:38 UTC, Hisataka-Hagiyama commented on module/ColorJudge.cpp
> +  int min = (rgb.r < rgb.g && rgb.r < rgb.b) ? rgb.r : (rgb.g < rgb.b) ? rgb.g : rgb.b;
個人的にはやっぱりこっちの方がわかりやすいです（短いので）
処理は変わらないのでお任せします。
```suggestion
  #include <algorithm>
  int max = std::max({rgb.r, rgb.g, rgb.b});
  int max = std::max({rgb.r, rgb.g, rgb.b});
```

2021-06-28 04:07 UTC, arimakaoru requested changes
環境を打ち消す処理が気になる
あと、もっとテストケースがほしい

2021-06-28 04:07 UTC, arimakaoru commented on test/ColorJudgeTest.cpp
> +namespace etrobocon2021_test {
最低でも各色につき、1テストケースはほしい

2021-06-28 04:07 UTC, arimakaoru commented on test/dummy/ColorSensor.h
> +    rgb_raw_t rawColor = { 8, 9, 10 };
メンバ変数として持つ意味がないから、test/dummy/ColorSensor.cppのgetRawColor関数の中で直接書いたら良いと思う

2021-06-28 04:22 UTC, Hisataka-Hagiyama commented on module/ColorJudge.h
> +  static constexpr rgb_raw_t MAX_RGB = { 112, 107, 152 };  //コースが白の時（最大）のRGB値
この値は明るさのパターン(4種類の照明*4段階)が変わると変わったりしますか？
明るさを変化させた場合に精度など変わったりするのでしょうか？

2021-06-28 11:52 UTC, Takahiro55555 reviewed
@arimakaoru が指摘した場所以外は大丈夫だと思います。

2021-06-28 19:31 UTC, miyashita64 commented on module/ColorJudge.cpp
> +  rgb.b = (_rgb.b < MAX_RGB.b) ? _rgb.b * 256 / MAX_RGB.b : 256;
すみません、言葉が悪かったです。環境光による、光の強さの偏りを軽減するための処理です。

シミュレータで白を測ると、rgb(112,107,152)のような青が強い値が出ます。白はRGBの値が一番大きいので、測定値が一番大きかった白をMAX_RGBに入れて、それをR,G,B,それぞれの最大値(255)として変換すれば、環境光の影響を軽減できそうだと考えました。
（例）
白（112, 107, 152）==変換==> 白( 255, 255, 255)
赤（103,   90, 128）==変換==> 赤( 235, 215, 215 )

2021-06-28 19:44 UTC, miyashita64 commented on module/ColorJudge.h
> +  static constexpr rgb_raw_t MAX_RGB = { 112, 107, 152 };  //コースが白の時（最大）のRGB値
コースで一番明るい値(測定値中の最大値)をMAX_RGBとしているので、環境によって変える必要があります。
実際に測定した結果、照明の明るさが最低の場合は(112, 107, 152), 最大の場合は(127, 116, 163)となっていました。
ただ、

2021-06-28 20:51 UTC, mutotaka0426 requested changes
細かい修正だけで，あとは全体的に良いと思う！

2021-06-28 20:51 UTC, mutotaka0426 commented on module/ColorJudge.cpp
> +  hsv = ColorJudge::getHsv(rgb);
```suggestion
  hsv = getHsv(rgb);
```
この記述って同じスコープ内だし冗長じゃない？
つけるとしたら`this->`だろうけど何もなくていいと思うよ

2021-06-28 20:51 UTC, mutotaka0426 commented on module/ColorJudge.cpp
> +ColorJudge::ColorJudge() {}
staticクラスではコンストラクタの実装部分は書かないほうがいいかな
コンストラクタをprivateにして非公開にしてくれているのは良いんだけど，それだけだとColorJudgeクラス内ではコンストラクタを呼び出してインスタンス化が出来ちゃうんだよね

基本的にColorJadgeクラス内でインスタンス化なんてしないだろうけど，staticクラスではインスタンス化そのものを禁止したいから，ここの部分は消去したほうがいい

2021-06-29 07:26 UTC, sugaken0528 requested changes

2021-06-29 07:26 UTC, sugaken0528 commented on test/ColorJudgeTest.cpp
> +
255, 255, 255も欲しいかな

2021-06-29 13:04 UTC, kodama0720 commented on module/ColorJudge.h
> +  ColorJudge();
コンストラクタいるんですか？

2021-06-30 01:23 UTC, arimakaoru commented on module/ColorJudge.h
> +} hsv_raw_t;
```suggestion
struct Hsv{
  int hue;         // 色相(0-360)
  int saturation;  // 彩度(0-100)
  int value;       // 明度(0-255)
};
```
C言語の構造体の書き方だね。
C++だとこういう風に書けるよ。実は、C++においてclassとstructはほとんど同じだから、何となくクラスっぽいものはclassで、構造体っぽいものはstructで書いてるらしい。
https://qiita.com/pink_bangbi/items/e25302df7f4ba7fa0db4

あと、型名は単純に`Hsv`でいいんじゃないかな〜
rgb_raw_tはC言語用のEV3APIで定義されているからこんな名前になっているけど、むしろこっちを`Rgb`っていう名前にしたい。 (しないけど)

2021-06-30 01:23 UTC, arimakaoru commented on module/ColorJudge.h
> +  static hsv_raw_t getHsv(rgb_raw_t const& rgb);
「get」だとgetterっぽいから、「変換する」ことがわかる名前がいいな
convertRgbToHsv
convertToHsv
rgbToHsv
とかどうかな？

2021-06-30 01:49 UTC, arimakaoru reviewed
@mutotaka0426 @Takahiro55555 @sugaken0528 @Hisataka-Hagiyama どうすれば良いと思う？

2021-06-30 01:49 UTC, arimakaoru commented on module/ColorJudge.cpp
> +  rgb.b = (_rgb.b < MAX_RGB.b) ? _rgb.b * 255 / MAX_RGB.b : 255;
取得したRGB値を、0〜255の値に正規化したいということだよね？
去年・一昨年に使った正規化の式は、[このサイト](https://mathwords.net/dataseikika#_M_m)の式なんだよね。
でも、今書いてる式でもできてそうな感じはする。
僕じゃわからないから、@mutotaka0426 @Takahiro55555 @sugaken0528 @Hisataka-Hagiyama がどうにかして！
こういうときに、識別精度を数字で出していたら、判断がしやすいんだよね...

このサイトの式を当てはめるならば、
xmin = 事前に取得した黒のRGB = MIN_RGB
xmax = 事前に取得した白のRGB = MAX_RGB
X = 今回取得したRBG = _rgb
m = 0 
M = 255
として、
```suggestion
  rgb.r = (_rgb.r < MAX_RGB.r) ? (_rgb.r - MIN_RGB.r) * 255 / (MAX_RGB.r - MIN_RGB.r) : 255;
  rgb.g = (_rgb.g < MAX_RGB.g) ? (_rgb.g - MIN_RGB.g) * 255 / (MAX_RGB.g - MIN_RGB.g) : 255;
  rgb.b = (_rgb.b < MAX_RGB.b) ? (_rgb.b - MIN_RGB.b) * 255 / (MAX_RGB.b - MIN_RGB.b) : 255;
```

2021-06-30 06:20 UTC, mutotaka0426 commented on module/ColorJudge.h
> +  ColorJudge();
ヘッダファイルに書かないと自動的にコンストラクタが生成されるみたいだから，ヘッダファイルに書いた上で実装部分を書かないようにしないといけないみたい

だからヘッダファイルにはコンストラクタは必要みたいだね

つまりMileageクラスのヘッダファイルにも書かないといけないみたいですねぇ！！

2021-06-30 09:09 UTC, miyashita64 commented on module/ColorJudge.h
> +  ColorJudge();
Mileageの修正は、このチケットでやった方がいいですか？

2021-06-30 09:12 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/132271)

2021-06-30 09:15 UTC, mutotaka0426 commented on module/ColorJudge.h
> +  ColorJudge();
このチケットではやらなくていいよ
次Mileage触る人が修正してくれたらいいかな

2021-06-30 09:20 UTC, miyashita64 commented on module/ColorJudge.cpp
> +  hsv.hue = (hsv.hue + 360) % 360;
遅くなりましたがこちらを参考に作りました
https://www.peko-step.com/tool/hsvrgb.html

R・G・Bのうち、最も大きな値をMAX、最も小さな値をMINとして

Rが最大値の場合 色相 H = 60 × ((G - B) ÷ (MAX - MIN))
Gが最大値の場合 色相 H = 60 × ((B - R) ÷ (MAX - MIN)) +120
Bが最大値の場合 色相 H = 60 × ((R - G) ÷ (MAX - MIN)) +240
3つとも同じ値の場合 色相 H = 0
求められた色相がマイナス値だった場合は360を加算して0～360の範囲に収めます

彩度 S = (MAX - MIN) ÷ MAX
明度 V = MAX

2021-06-30 09:22 UTC, Takahiro55555 approved these changes
![LGTM](https://image.lgtmoon.dev/131983)

2021-06-30 10:14 UTC, Hisataka-Hagiyama commented on module/ColorJudge.cpp
> +  rgb.b = (_rgb.b < MAX_RGB.b) ? _rgb.b * 255 / MAX_RGB.b : 255;
@miyashita64 @hiroto0927 
2人がどういう資料を参考にこの式を書いているのか、またはどういう意図で書いているのか知りたいです。
xminを0にしたら @arimakaoru が添付してくださった資料の式になるみたいですけど0にしていいんですか？

2021-06-30 11:04 UTC, miyashita64 commented on module/ColorJudge.cpp
> +  rgb.b = (_rgb.b < MAX_RGB.b) ? _rgb.b * 255 / MAX_RGB.b : 255;
最低値を測って引く方が正しいと思います。
単純に最小値側の正規化を失念していました。

2021-06-30 12:41 UTC, Hisataka-Hagiyama approved these changes
![LGTM](https://image.lgtmoon.dev/132294)

2021-06-30 13:15 UTC, arimakaoru approved these changes
![LGTM](https://image.lgtmoon.dev/132305)

2021-06-30 14:29 UTC, sugaken0528 approved these changes
LGTM!!

2021-06-30 14:29 UTC, sugaken0528 commented on module/ColorJudge.cpp
> +  hsv.hue = (hsv.hue + 360) % 360;
ありがと!!
今後はプルリク出すときに参考資料にあげといて!

2021-06-30 14:32 UTC, merged