Update: LineTracerクラスにrunByRgb()を追加
KatLab-MiyazakiUniv/etrobocon2021 pull request #78
Opened 2021-06-27 10:14 UTC by miyashita64

# チェックリスト

- [x] clang-format している
- [] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
- LineTracerクラスに、白黒を識別している間、ライントレースするrunByRgb()を追加
- 「色を取得・識別する」がないため、コンパイル・テストは通らない。(あれば通った)

# 動作テスト

## 実験方法
- 「色を取得・識別する」を反映し、テストした
- ライントレースエリア(ゴール付近の青線まで)を3回ライントレースした
- ブロックビンゴエリアにて、ライン上の各色(黄、赤、青、緑)について、10回ずつライントレースした

## 実験結果
- ライントレースで、ライントレースエリアを完走できた。
- いずれも、白黒以外の色に入った時点で停止した。

## 添付資料

https://user-images.githubusercontent.com/83441177/123540592-c79eff00-d77a-11eb-8896-dddcf6edbe22.mp4

2021-06-28 04:44 UTC, arimakaoru reviewed
だいたいOK!

2021-06-28 04:44 UTC, arimakaoru commented on module/LineTracer.cpp
> +  COLOR color;
初期化は必ずしたい
```suggestion
  COLOR color = COLOR::None;
```

2021-06-28 04:44 UTC, arimakaoru commented on module/LineTracer.cpp
> +  //走行距離が目標距離に到達するまで繰り返す
変更忘れ

2021-06-28 05:54 UTC, Hisataka-Hagiyama reviewed
コードの内容に関しては問題ないと思います。
GitHub上でのチェックが通るようになったら再度確認します。

2021-06-28 10:02 UTC, Takahiro55555 requested changes
処理は大丈夫だと思います。

2021-06-28 18:01 UTC, sugaken0528 reviewed
オッケーだと思います
色識別のレビュー急ぎます

2021-06-30 14:51 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/23721)

2021-06-30 15:00 UTC, Hisataka-Hagiyama approved these changes
![LGTM](https://image.lgtmoon.dev/132321)

2021-06-30 15:04 UTC, sugaken0528 approved these changes
![LGTM](https://image.lgtmoon.dev/132324)

2021-06-30 23:23 UTC, uchyam approved these changes
LGTM

2021-07-01 00:38 UTC, arimakaoru approved these changes

2021-07-01 01:24 UTC, Takahiro55555 approved these changes

2021-07-01 01:24 UTC, merged