close #67 直進・後退する
KatLab-MiyazakiUniv/etrobocon2021 pull request #79
Opened 2021-06-27 13:16 UTC by hiroto0927

# チェックリスト

- [x] clang-format している
- [ ] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
直進・後退するクラス（Straighter）を作成。
指定距離を直進・後退する関数(straight())を作成。
白黒以外を検知するまで直進・後退する関数(straightByColor())を作成。

# 動作テスト

## 実験方法
ブロックビンゴエリアに走行体を設置し、走行体が色を認識するまで直進（後退）させる。
指定した距離（1050mm）を直進（後退）する。

## 実験結果
白黒以外の色を認識すると走行体が止まった（直進と後退）

指定した距離（1050mm）を進んだ（直進と後退）
ただし、多少右へのずれあり。

## 添付資料

https://user-images.githubusercontent.com/83230897/123544256-60d71100-d78d-11eb-9f3c-4cd3cbf95d34.mp4

https://user-images.githubusercontent.com/83230897/123544251-5ddc2080-d78d-11eb-9e19-02f629e5d938.mp4

https://user-images.githubusercontent.com/83230897/123545555-8f57ea80-d793-11eb-983e-549197b5bf9b.mp4

https://user-images.githubusercontent.com/83230897/123545845-23768180-d795-11eb-99e0-02d3baa48d06.mp4

2021-06-28 05:09 UTC, arimakaoru reviewed
だいたいOK!

2021-06-28 05:09 UTC, arimakaoru commented on module/Straighter.cpp
> +  // 走行距離が目標距離に到達するまで繰り返す
変更忘れ

2021-06-28 05:32 UTC, Hisataka-Hagiyama commented on module/Straighter.h
> +  void straight(double targetDistance, int pwm);
関数名は動詞＋名詞（名詞は省略可）となっていますが、straightは動詞として使われるものでないと思うので不適切かなと思います。

2021-06-28 05:32 UTC, Hisataka-Hagiyama commented on module/Straighter.h
> +  void straightByColor(int pwm);
同じくstraightという単語は不適切かなと思います。

2021-06-28 09:51 UTC, Takahiro55555 requested changes
処理などは大丈夫だと思います。

2021-06-28 09:51 UTC, Takahiro55555 commented on module/Straighter.h
> +  void straightByColor(int pwm);
あと、`ByColor`ではなく、`ToColor`にしたほうが良いかもしれません。

> １－１．場所や時間（期間・日付）にも使える「to」で「～まで」

参考：[「～まで」の英語｜４つのパターンと期間や距離などで使える例文一覧 | マイスキ英語](https://mysuki.jp/english-until-22327)

2021-06-28 11:20 UTC, kodama0720 reviewed
Straighterも名詞ではなさそうです。

2021-06-28 16:24 UTC, sugaken0528 commented
処理は良いと思います
動画と一緒に出力も載せてくれてるから色識別については何となく出来てるっていうのが分かったけど、動画載せる時は、カラーセンサーの位置とか、走行体のズレがわかりやすいような角度で記録してもらえるともっと良いかも。
今回はとりまオッケ。

2021-06-28 16:24 UTC, sugaken0528 commented on module/Straighter.h
> +  void straight(double targetDistance, int pwm);
moveStraightとかいんじゃ?

2021-06-28 16:24 UTC, sugaken0528 commented on module/Straighter.h
> +  void straightByColor(int pwm);
moveStraightToColorとかいんじゃ?

2021-06-28 16:48 UTC, hiroto0927 commented
> 処理は良いと思います
> 動画と一緒に出力も載せてくれてるから色識別については何となく出来てるっていうのが分かったけど、動画載せる時は、カラーセンサーの位置とか、走行体のズレがわかりやすいような角度で記録してもらえるともっと良いかも。
> 今回はとりまオッケ。

カメラ角度を走行体の正面から撮影したいと思ったのですがカメラ角度の変更がわかりませんでした。
カメラ角度の変更はどのようにすればいいですか？

2021-06-28 16:54 UTC, sugaken0528 commented
シミュレータのUI上を右クリックしながらスライドすると色んな角度で見れるよ
あとマウスのホイールで拡大縮小できる

2021-06-30 14:58 UTC, mutotaka0426 requested changes
すげぇ今更なんやけど，テストコード書いてなかったんやね
気づかなかったわごめん

回頭・ピボットターンみたいにテストコードも書いてほしいから，このチケットは持ち越そう

2021-07-01 01:00 UTC, arimakaoru approved these changes

2021-07-01 01:26 UTC, Takahiro55555 approved these changes

2021-07-01 02:01 UTC, kodama0720 approved these changes

2021-07-01 11:12 UTC, mutotaka0426 requested changes

2021-07-01 11:12 UTC, mutotaka0426 commented on module/StraightRunner.cpp
> +
pwmに0を指定されたときと，targetDistanceとpwmの符号が一致してないと無限ループになるよね？
で回避できないかな
```
if(prm == 0 && std::signbit(targetDistance) == std::signbit(pwm)) return;
```

2021-07-02 05:25 UTC, hiroto0927 commented on module/StraightRunner.cpp
> +
pwmが0の時は無限ループすると思うので修正します。

質問になるんですが、targetDistanceとpwmの符号が一致してない時での無限ループするとのことですが、pwmの符号を-にして後退するような関数にしています。
符号が違う時での無限ループする時がイマイチわかりません、、、

2021-07-03 07:12 UTC, yutotanaka24 approved these changes

2021-07-03 07:40 UTC, mutotaka0426 approved these changes
lgtm

2021-07-03 07:41 UTC, merged