ビンゴエリアクラス
KatLab-MiyazakiUniv/etrobocon2021 pull request #87
Opened 2021-07-08 06:00 UTC by Hisataka-Hagiyama

# チェックリスト

- [x] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
Measurer.h、Measurer.cppにコース情報取得用APIを追加
Nodeクラス、BlockCircleクラス、CrossCircleクラス、CenterMarkクラスを追加

# 動作テスト

## 実験方法

## 実験結果

## 添付資料

2021-07-08 08:03 UTC, Hisataka-Hagiyama reviewed
プルリクの際にはブロックに番号を振った図を添付する

2021-07-08 08:03 UTC, Hisataka-Hagiyama commented on module/BingoArea.cpp
> +void BingoArea::setBlockInfo(int info, int blockId, COLOR color)
switch文にdefaultの処理を追加

2021-07-12 03:45 UTC, arimakaoru requested changes
ブロックIDとサークルIDを使って、別のクラスとやり取りするの？
座標を使うかと思ってた。

2021-07-12 03:45 UTC, arimakaoru commented on module/BingoArea.cpp
> +      }
上から順番に1回ずつif文の中に入るよね？
`std::array<COLOR, 8> blockCircleColors = {COLOR::YELLOW, COLOR::GREEN, ... 略};`
を用意しておいて、順番に代入していくだけでいいんじゃない？
CIRCLE_IDも同じく
メリット
- コードが短くなる
- 実行時に、if文を上から確認していく処理がなくなる

2021-07-12 03:45 UTC, arimakaoru commented on module/BingoArea.h
> +  void setBlockInfo(int info, COLOR color);
initBingoArea関数からしか呼び出さないから、privateでいいかも？

2021-07-12 03:45 UTC, arimakaoru commented on module/BingoArea.h
> +  Node& getBlockInfo(BLOCK_ID blockId);
名前がイマイチ
@briefによると、この関数の役割は「ブロックの情報を取得する」ではなく、「ブロックが置かれているノードの情報を取得する」だから、`getNode`でよくない？
あと、`Info`って付けなくてよいと思うな

2021-07-12 04:33 UTC, mutotaka0426 requested changes

2021-07-12 04:33 UTC, mutotaka0426 commented on module/BingoArea.cpp
> +      int initEfgeNumber = 0;
```suggestion
      std::array<std::array<COLOR, 4>, 4> initCircleColor = {{COLOR::RED, COLOR::RED, COLOR::BLUE, COLOR::BLUE},
                                                             {COLOR::RED, COLOR::RED, COLOR::BLUE, COLOR::BLUE},
                                                             {COLOR::YELLOW, COLOR::YELLOW, COLOR::GREEN COLOR::GREEN},
                                                             {COLOR::YELLOW, COLOR::YELLOW, COLOR::GREEN COLOR::GREEN}};
      std::array<std::array<int, 4>, 4> initEdgeNumber = {{2, 3, 3, 2},
                                                          {3, 4, 4, 3},
                                                          {3, 4, 4, 3},
                                                          {2, 3, 3, 2}};
```
みたいにしたら，`crossCircle[index].setCicleColor(initCircleColor[i][j]);`ってするだけでセットできないかな
この方がif文が消えて視覚的にも処理的にもわかりやすくなると思うんだけどどうですか

2021-07-12 04:33 UTC, mutotaka0426 commented on module/BingoArea.cpp
> +      crossCircle[index].setEdgeNumber(initEfgeNumber);
```suggestion
      crossCircle[index].setEdgeNumber(initEdgeNumber);
```
スペルミス？

2021-07-12 04:33 UTC, mutotaka0426 commented on module/BingoArea.cpp
> +    }
ここの各case文の中で三項演算子書いてるけど，infoが決まってればIS_LEFT_COURSEは一意に決まるよね
（infoが65のとき，IS_LEFT_COURSEは必ず偽である等）
これはなんかキレイに書けそうな気がするけどちょっと解決案は思いつかない

2021-07-12 08:35 UTC, miyashita64 requested changes

2021-07-12 08:35 UTC, miyashita64 commented on module/BingoArea.cpp
> +      crossCircle[index].setCoordinate(i, j);
i→y, j→x になっているので、引数が逆です。

2021-07-12 08:35 UTC, miyashita64 commented on module/BingoArea.cpp
> +      blockCircle[index2].setCoordinate(i, j);
ここも、引数逆になると思います。

2021-07-13 07:40 UTC, sugaken0528 requested changes

2021-07-13 07:40 UTC, sugaken0528 commented on module/BingoArea.cpp
> +      int initEfgeNumber = 0;
Efge→Edge?

2021-07-13 07:55 UTC, arimakaoru approved these changes
LGTM!!

2021-07-13 09:58 UTC, Takahiro55555 approved these changes
LGTM!!!


おまけ
`module/BingoArea.cpp`をレビューする際に参考にした資料です。
プルリクの参考資料にも添付しておいたほうが良いかも!?

- [sim_extended_api - ブロックの位置情報について](https://github.com/ETrobocon/etrobo/wiki/sim_extended_api#%E3%83%96%E3%83%AD%E3%83%83%E3%82%AF%E3%81%AE%E4%BD%8D%E7%BD%AE%E6%83%85%E5%A0%B1%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6)

2021-07-13 09:58 UTC, Takahiro55555 commented on module/BingoArea.cpp
> +    }
```suggestion
    int offset = 65;
    std::array<int, 19> leftIndexTable
        = {0, 1, 2, 3, 4, 5, 6, 7, -1,  8,  9, 10, 11, -1, -1, 12, 13, 14, 15};
    //     A, B, C, D, E, F, G, H,  _,  J,  K,  L,  M,  _,  _,  P,  Q,  R,  S

    std::array<int, 19> rightIndexTable 
        = {3, 2, 1, 0, 7, 6, 5, 4, -1, 11, 10,  9,  8, -1, -1, 15, 14, 13, 12};
    //     A, B, C, D, E, F, G, H,  _,  J,  K,  L,  M,  _,  _,  P,  Q,  R,  S

    std::array<BLOCK_ID, 19> blockIdTable
        = {BLOCK_ID::ID0, BLOCK_ID::ID0, BLOCK_ID::ID0, BLOCK_ID::ID1, BLOCK_ID::ID2, 
          BLOCK_ID::ID0, BLOCK_ID::ID3, BLOCK_ID::ID0, BLOCK_ID::ID0, BLOCK_ID::ID0, 
          BLOCK_ID::ID4, BLOCK_ID::ID0, BLOCK_ID::ID5, BLOCK_ID::ID0, BLOCK_ID::ID0, 
          BLOCK_ID::ID6, BLOCK_ID::ID0, BLOCK_ID::ID7};

    if (IS_LEFT_COURSE ) {
        index = leftIndexTable[info - offset];
    } else {
        index = rightIndexTable[info - offset];
    }
    blockId = blockIdTable[info - offset];
```

個人的に色々試してみたけど、既にあるswitch文と変換テーブルを作成する以外にまともなものが思いつかなかった...

自分は、変換テーブルよりもswitch文のほうが見やすいから、このままのほうがよいと思います。

2021-07-13 10:38 UTC, sugaken0528 requested changes
処理はOKと思います。

2021-07-13 14:56 UTC, sugaken0528 approved these changes
![LGTM](https://image.lgtmoon.dev/133909)

2021-07-13 18:44 UTC, mutotaka0426 requested changes
BLOCK_IDは良いと思うんだけど，CIRCLE_IDの役割が良く分からない
俺が何か勘違いしてるかもしれないから説明よろしくお願いします

2021-07-13 18:44 UTC, mutotaka0426 commented on module/BingoArea.cpp
> +}
ここの処理が良く分かんないんだけど，↓みたいな処理ではダメ?
あと，CIRCLE_IDって0~7ってNode.hで書いてあるけど，この処理だと8まで行かない？

他でblockCircleを使ってるところ見てみても，blockCicleのインデックスをそのままIDとして扱えるような気がするんだけど，そもそもCIRCLE_IDって何のためにあるの？


```suggestion
  int index4 = 0;
  for(int y = 0; y < 3; y ++) {
    for(int x = 0; x < 3; x ++) {
      if(x == 1 && y == 1) {
        centerMark.setCoordinate(x * 2 + 1, y * 2 + 1);
        centerMark.setCircleColor(COLOR::BLACK);
      }else {
        blockCircle[index4].setCoordinate(x * 2 + 1, y * 2 + 1);
        blockCircle[index4].setCircleColor(blockCircleColor[index4]);
        blockCircle[index4].setCircleId(static_cast<CIRCLE_ID>(index4));
      }
    }
  }

```

2021-07-13 18:44 UTC, mutotaka0426 commented on module/BingoArea.h
> +   *@param circleId ブロック番号
```suggestion
   *@param circleId ブロックサークルID

```
かな？
ここってIDをそのままint型にcastしてるだけみたいだし，getCrossCircleと同じようにindexでもいいんじゃないって思ったんだけど，何が違うの？
blockCircleのインデックスとcircleIdの違いが良く分からない

2021-07-14 00:34 UTC, uchyam commented on module/BingoArea.cpp
> +  }
こっちの処理の方が理解しやすいので変更します

2021-07-14 03:26 UTC, mutotaka0426 commented on module/BingoArea.cpp
> +  }
`index++;`忘れてたわ

2021-07-14 03:27 UTC, mutotaka0426 commented on module/BingoArea.cpp
> +}
こっちも`index4++`してなかった

2021-07-14 10:28 UTC, uchyam commented on module/BingoArea.cpp
> +}
int型よりenum classの方が-1〜7で制限されるから安全。という理由でCIRCLE_IDを作りました

2021-07-14 14:12 UTC, mutotaka0426 requested changes
なんかもうenumが良く分からない

2021-07-14 14:12 UTC, mutotaka0426 commented on module/Node.h
> +  SIZE = 8,
0 ~ 7しか選べないようにして安全にしたいってのは分かったんだけど，ここの`SIZE = 8`があるから8を入れてもエラーにならなかったんじゃないの？enumにSIZEっての持たせる記述って一般的？これが邪魔してない？
-1 ~ 8まで選べるようになってるなら安全じゃないと思うんだけど

2021-07-14 14:12 UTC, mutotaka0426 commented on module/Node.h
> +  SIZE = 8,
こいつも

2021-07-15 05:28 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/133792)

2021-07-15 06:39 UTC, miyashita64 approved these changes
LGTM

2021-07-15 08:00 UTC, merged