Ticket 82
KatLab-MiyazakiUniv/etrobocon2021 pull request #88
Opened 2021-07-08 07:30 UTC by kodama0720

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
-BingoMotionクラス、ToCrossMotionクラス、InCrossMotionクラス、SetColorBlockMotionクラス作成
-ControllerとMeasurerにアームの動きを追加

# 動作テスト

## 実験方法

## 実験結果

## 添付資料

2021-07-10 13:29 UTC, kodama0720 commented on module/InCrossMotion.cpp
> +  }
エッジを逆にする処理がうまくいかなかったのですが、上のように線の逆側にずらしてエッジを変えずに進むようにしたら都合悪いことありますか？

2021-07-11 00:23 UTC, arimakaoru commented on module/InCrossMotion.cpp
> +  }
動作にかかる時間と、動作の成功率が良いなら、この動きでも有りだと思う

2021-07-12 04:34 UTC, arimakaoru requested changes
動画では、想像以上に綺麗に動いていて良かった！

疑問点
- PWM=30をベースにしてるけど、もっと上げられそうか
- 各動作の成功率はどのくらいか

2021-07-12 04:34 UTC, arimakaoru commented on module/Controller.h
> +  void stopArmMotor();
（オプション）
PWM値をセットする関数と、停止する関数に分けるのではなく、
車輪を制御する関数と、アームを制御する関数で分けた方が、このクラスを使う人が探しやすくない？

2021-07-12 04:34 UTC, arimakaoru commented on module/InCrossMotion.cpp
> +  int targetDistance = 140.0;
ここにも、交点サークルの外径分の値であることを書いた方が良いと思う
コメントで書くか、変数名を変えるか

2021-07-12 04:34 UTC, arimakaoru commented on module/InCrossMotion.cpp
> +  // int angle = 180;
いらない？

2021-07-12 04:34 UTC, arimakaoru commented on module/InCrossMotion.cpp
> +  //直進する
なぜ左に進むときだけ、直進が必要なのか不思議だから、コメントで補足してほしい
`// エッジを切り替えないようにするために、直進する`

コメントでは、以下のことを書くのが個人的なおすすめ
- 処理を抽象化したコメント
- その処理をする理由

2021-07-12 04:34 UTC, arimakaoru commented on module/SetColorBlockMotion.cpp
> +    printf("%d\n", measurer.getArmMotorCount());
消し忘れ？

2021-07-12 04:34 UTC, arimakaoru commented on module/SetColorBlockMotion.cpp
> +    printf("%d\n", measurer.getArmMotorCount());
消し忘れ？
デバッグのときはいいけど、本番ではprintfは避けたい

2021-07-12 04:34 UTC, arimakaoru commented on module/ToCrossMotion.h
> +   * @brief 交点間を移動する
```suggestion
   * @brief 交点サークル間を移動する
```

2021-07-13 07:46 UTC, arimakaoru approved these changes
LGTM!!

2021-07-13 17:44 UTC, sugaken0528 commented on module/InCrossMotion.cpp
> +}
左コースの場合、右折するときは走行体から見て黒線の延長戦の手前(issueの図1)まで直進して、90度ピボットターン。
左折するときは走行体から見て黒線の延長戦の奥(issueの図1+黒線の太さ)まで直進して、90度ピボットターンじゃなかったかね?
動画では上手くいってるみたいだけど上記の動作でも試した感じ?

2021-07-13 17:44 UTC, sugaken0528 commented on module/SetColorBlockMotion.cpp
> +}
元の位置に戻った状態が終了状態だっけ?
投げてそのままの状態が終了状態だった気が、、
となると方向転換って動作が別にいるけどどうでしたっけ?
@arimakaoru

2021-07-13 20:59 UTC, Takahiro55555 approved these changes
LGTM

2021-07-14 09:41 UTC, kodama0720 commented on module/InCrossMotion.cpp
> +}
回頭でなくピボットターンなので図１の距離直進は必要ないと思います。
黒線の太さ分直進は右コースの場合で分ける必要がありますね。

2021-07-14 19:19 UTC, sugaken0528 commented on module/InCrossMotion.cpp
> +}
ごめん、図１の距離直進じゃなくて、黒線の太さ分直進せんと理論上黒線上にのれん

2021-07-15 02:42 UTC, arimakaoru commented on module/SetColorBlockMotion.cpp
> +}
どちらでも可
どっちにするかは要検討

2021-07-15 06:06 UTC, kodama0720 commented on module/InCrossMotion.cpp
> +}
動かしてみた感じだと直進しない時にちょうどいい位置に乗っています。
動いているうちに走行体のアームが内側を向いていくせいかもしれません。
色判定がうまくできないのもそれが原因の気がします。

2021-07-27 02:49 UTC, mutotaka0426 requested changes
細かい修正はあるけど全体的にはいいと思う

2021-07-27 02:49 UTC, mutotaka0426 commented on module/InCrossStraight.h
> + * @brief 交点内移動のクラス
.cppと統一しようか
```suggestion
 * @brief 交点内移動（直進）のクラス
```

2021-07-27 02:49 UTC, mutotaka0426 commented on module/InCrossRight.cpp
> + * @brief 交点内移動（右）のクラス
InCrossLeftと合わせて右折で
```suggestion
 * @brief 交点内移動（右折）のクラス
```

2021-07-27 02:49 UTC, mutotaka0426 commented on module/InCrossRight.h
> + * @brief 交点内移動（右）のクラス
ここも

2021-07-27 02:49 UTC, mutotaka0426 commented on module/DirectionChanger.cpp
> +  // straightRunner.runStraightToBlackWhite(runPwm);
忘れるからコメントアウトしなくていいよ

2021-07-27 02:49 UTC, mutotaka0426 commented on module/Controller.h
>    void stopMotor();
アームのモータもあるしこの名前はよくなかったねゴメン
ちょっと面倒かもしれないけど`stopArmMoto()`と同じように修正お願いします
```suggestion
   * タイヤのモータを停止する
   */
  void stopWheelMotor();
```

2021-07-27 02:49 UTC, mutotaka0426 commented on module/Controller.cpp
>  void Controller::stopMotor()
ここも
```suggestion
//タイヤのモータを停止する
void Controller::stopWheelMotor()
```

2021-07-28 09:28 UTC, mutotaka0426 requested changes
ごめん追加で修正よろしくお願いします

2021-07-28 09:28 UTC, mutotaka0426 commented on module/BlockPivotTurn.h
> +  void setBlockPivotTurn(bool isLeft);
ごめん，これ今考えるとisLeftって分かりづらいわ
edgeだったりcourseだったりあるわけだからもっと明示的に書いた方がいいわ
isClockwiseとかの方が良くない？cppのif文が逆になりそうだけど
```suggestion
  void setBlockPivotTurn(bool isClockwise);
```

2021-07-28 09:28 UTC, mutotaka0426 commented on module/BlockPivotTurn.cpp
> +    controller.stopArmMotor();
ここの記述はちょっとおかしい気がしてきた
関数に分けるか，アーム制御用のクラスを用意したほうがいい気がしてきた
投げ入れ設置でも使うことを考えたら，個人的には後者の方がいいな

2021-07-28 09:28 UTC, mutotaka0426 commented on module/BlockThrower.h
> +  void throwBlock(bool isLeft);
ここもisClockwiseの方がいいと思う

2021-07-28 09:28 UTC, mutotaka0426 commented on module/BlockPivotTurn.cpp
> + * @brief カラーブロック設置クラス
```suggestion
 * @brief ピボットターン設置クラス
```

2021-07-28 12:42 UTC, sugaken0528 requested changes
build通ってないで

2021-07-28 12:42 UTC, sugaken0528 commented on module/BlockPivotTurn.h
> +   * @param isClockwise ピボットターンする向き true: 右向き
isClockwiseの説明で「右向き」はちょい違和感

2021-07-28 13:21 UTC, kodama0720 commented on module/BlockPivotTurn.h
> +   * @param isClockwise ピボットターンする向き true: 右向き
buildは直進クラスに黒白まで直進する関数を入れたら出来ると思います。
それと、ちょっと今WSLの接続エラーが起きてて修正に時間がかかりそうです。

2021-07-29 07:00 UTC, mutotaka0426 approved these changes
lgtm

2021-07-29 07:03 UTC, sugaken0528 approved these changes

2021-07-29 07:06 UTC, Hisataka-Hagiyama approved these changes
LGTM

2021-07-29 07:06 UTC, miyashita64 commented on module/InCrossRight.cpp
> +  straightRunner.runStraightToDistance(15, 20);
ほかの関数や、InCrossLeftではtargetDistance, runPwmを使っていたので、合わせたほうがいいと思います。

2021-07-29 07:25 UTC, miyashita64 approved these changes
LGTM!!

2021-07-29 07:25 UTC, merged