close #83 黒ブロック運搬
KatLab-MiyazakiUniv/etrobocon2021 pull request #90
Opened 2021-07-08 07:36 UTC by yutotanaka24

# チェックリスト

- [x] clang-format している
- [x] コーディング規約に準じている
- [x] チケットの完了条件を満たしている

# 変更点
BlackBlockCarrier.cpp
BlackBlockCarrier.h
の追加
ETRobocon2021.cppの変更
# 動作テスト

## 実験方法

## 実験結果

## 添付資料

2021-07-12 05:35 UTC, arimakaoru reviewed
コードはだいたい良さそう！
現状の動画がみたいな

2021-07-12 05:35 UTC, arimakaoru commented on module/EtRobocon2021.cpp
> +  BlackBlockCarrier::carryBlackBlock();
最終的には、ここで呼び出す訳ではないから、これはプルリクに含めないでほしい
（自分のPCで作業するときはここに書いていいけど）

2021-07-13 17:47 UTC, sugaken0528 commented
今の所どのくらいできるのか動画を載せてちょうだいな
それあると皆アドバイスしやすいと思う

2021-07-13 18:35 UTC, yutotanaka24 commented
> 今の所どのくらいできるのか動画を載せてちょうだいな
> それあると皆アドバイスしやすいと思う

とても遅くなってしまい申し訳ありません。

2021-07-13 18:51 UTC, mutotaka0426 commented
今回は精度は問わないけど，最後中途半端なところで終わってるのは
動作の流れはだいたい出来てそうだからいいと思うんだけど，最後は距離調整はしてないだけ？あとセンターブロックに黒ブロック置いた後は黒線まで下がる動作もあるんじゃない？

2021-07-13 18:53 UTC, mutotaka0426 requested changes
今回は精度は問わないけど，最後かなり中途半端なところで終わってない？距離調整してないだけ？
あとセンターブロックに黒ブロック置いた後は黒線まで下がる動作もあるんじゃないっけ？

2021-07-13 18:53 UTC, mutotaka0426 commented on module/EtRobocon2021.h
> +#include "BlackBlockCarrier.h"
消し忘れ？

2021-07-13 19:38 UTC, yutotanaka24 commented on module/EtRobocon2021.h
> +#include "BlackBlockCarrier.h"
同じ距離を設定してても結構位置がずれるので、微妙な位置で終わってました。黒線まで下がる動作はミスで書いてませんでした。

消し忘れです

2021-07-14 13:11 UTC, sugaken0528 commented
動画見ました
なんかもうちょい距離を延ばせばいいだけな気がするけどそんなうまくいかんもん?

2021-07-15 10:52 UTC, Hisataka-Hagiyama commented on etrobo-log.txt
> +make: *** No rule to make target 'sim'.  Stop.
このファイル(etrobo-log.txt)はリモートのetrobocon2021に無いみたいなので削除しておいた方がいいのかなと思います
遅くなって申し訳ないです

2021-07-15 11:40 UTC, yutotanaka24 commented
一応真ん中まで黒ブロックを運ぶことができました。黒ブロックを取得するところまでは割と安定しているのですが、運ぶ動作がまだ不安定です。

https://user-images.githubusercontent.com/83375723/125782002-238ddac6-6bde-4874-843e-e8653da3e0ad.mp4

2021-07-15 12:44 UTC, Hisataka-Hagiyama commented on module/BlackBlockCarrier.cpp
> +  double secondBlackDistance = 760.0;
この値は定数だと思うのでconst修飾子をつけておかなくて大丈夫ですか？
runPwmとtargetBrightnessも変わらない値ですか？
このクラスではconstをつける必要はないのでしょうか？

2021-07-15 13:25 UTC, sugaken0528 requested changes

2021-07-15 13:25 UTC, sugaken0528 commented on module/BlackBlockCarrier.cpp
> +  double secondBlackDistance = 760.0;
```suggestion
  constexpr int runPwm = 50;
  constexpr int targetBrightness = 12;
  constexpr double circleDistance = 150.0;
  constexpr double firstBlackDistance = 420.0;
  constexpr double secondBlackDistance = 760.0;
```

2021-07-15 14:13 UTC, mutotaka0426 requested changes
定数化するなら名前も定数仕様にして

2021-07-15 14:13 UTC, mutotaka0426 commented on module/BlackBlockCarrier.cpp
> +  constexpr double secondBlackDistance = 760.0;
```suggestion
  constexpr int RUN_PWM = 50;
  constexpr int TAEGET_BRIGHTNESS = 12;
  constexpr double CIRCLE_DISTANCE = 150.0;
  constexpr double FIRST_BLACK_DISTANCE = 420.0;
  constexpr double SECOND_BLACK_DISTANCE = 760.0;
```

2021-07-15 14:23 UTC, sugaken0528 commented on module/BlackBlockCarrier.cpp
> +  constexpr double secondBlackDistance = 760.0;
すまん

2021-07-15 14:25 UTC, Hisataka-Hagiyama reviewed
できればプルリクのチェックリストにチェックを入れておいてほしいです。見たところ各項目は満たしているみたいですが。（担当者以外がチェックを入れるのも良くない気がしますし、チェックされてないのも好ましくない気がします）

2021-07-15 14:25 UTC, Hisataka-Hagiyama commented on module/BlackBlockCarrier.cpp
> +  PidGain rungain(1.5, 1, 1.5);
もしかするとこの部分も定数として扱うものでしょうか？

2021-07-15 14:36 UTC, sugaken0528 requested changes

2021-07-15 14:36 UTC, sugaken0528 commented on module/BlackBlockCarrier.cpp
> +  straightrunner.runStraightToDistance(60, 40);
緑の縁の中心までの定数もいるくない?

2021-07-15 14:36 UTC, sugaken0528 commented on module/BlackBlockCarrier.cpp
> +  straightrunner.runStraightToDistance(250, runPwm);
そういえば青線って普通のライントレースでできないの?
去年はできてたはずだけど

できないとして、青の線の距離もCIRCLE_DISTANCE, FIRST_BLACK_DISTANCE, SECOND_BLACK_DISTANCEみたいに定数化はしないの?

何を定数として何を定数としないのかの基準とかある?

2021-07-15 14:37 UTC, mutotaka0426 approved these changes
ｌｇｔｍ

2021-07-15 14:45 UTC, yutotanaka24 commented on module/BlackBlockCarrier.cpp
> +  straightrunner.runStraightToDistance(250, runPwm);
ライントレースは青線に入るとできませんでした、、、
明確な基準はないのでそろえようと思うのですすべて定数化した方がいいですかね？

2021-07-15 14:50 UTC, sugaken0528 commented on module/BlackBlockCarrier.cpp
> +  straightrunner.runStraightToDistance(250, runPwm);
あ、そうなんや
やるなら全部定数にした方が良いと思う!!
変数名の付け方に気をつけてね!!

2021-07-15 14:51 UTC, yutotanaka24 commented on module/BlackBlockCarrier.cpp
> +  PidGain rungain(1.5, 1, 1.5);
見落としてました、固定なので定数として扱ってます

2021-07-15 15:59 UTC, Hisataka-Hagiyama commented on module/BlackBlockCarrier.cpp
> +  const PidGain RUN_GAIN(1.5, 1, 1.5);  //直進のライントレースに使用するゲイン
ここだけconstなのは書き間違いですか？

2021-07-15 16:07 UTC, miyashita64 commented on module/BlackBlockCarrier.cpp
> +  linetracer.runToColor(TARGET_BRIGHTNESS, RUN_PWM, RUN_GAIN);
ここ以降のRUN_PWM(=50)には、もともと60が入ってましたが、意図的に下げてますか？

2021-07-15 16:20 UTC, sugaken0528 commented
んー、確かに全部とはいったけどめちゃめちゃやったね。
まず角度は定数にしなくて良い。ターンPWM値も定数じゃなくて良い。
最初は直進距離が定数であるものとそうでないものとでバラバラだったから統一化して欲しくて距離を定数にしてもらおうと思っただけ。
TARGET_BRIGHTNESS, GAIN, RUN_GAINは確かに定数でいいかな。

で、RUN_PWM=50っていう直進で使ってるPWM値の定数があるにも関わらずTO_BLACK_LINE_PWM=20, TO_BLACK_BLOCK_PWM=30があるのはよくわからないね。
RUN_PWMをBASE_PWMっていう定数名にして、これをPWM値の基準として、BASE_PWM-30とかBASE_PWM-20とかにするならわかる。

今コードの見た目が結構気持ち悪いから、もう距離も定数化しなくていいや。

まとめ
定数にするのはTARGET_BRIGHTNESS, GAIN, RUN_GAIN, RUN_PWMのみで良いと思う。
あとclang formatしてね。

2021-07-15 16:26 UTC, Takahiro55555 requested changes

2021-07-15 16:26 UTC, Takahiro55555 commented on module/BlackBlockCarrier.cpp
> +  const PidGain RUN_GAIN(1.5, 1, 1.5);  //直進のライントレースに使用するゲイン
個人的に気になった部分を修正してみました。

座標系に関してですが、シミュレータに倣うならY軸は上下方向になるので不味いと思います。

あと、各定数でどの様な値（距離なのか角度なのかといったこと）が分からないものがあったので、一部修正しています。

`GREEN_CIRCLE_DISTANCE ` を `GREEN_CIRCLE_CENTER_POINT_DISTANCE` への変更を提案していますが、長すぎるのでこのままでもよいと思います。

```suggestion
  constexpr int RUN_PWM = 50;
  constexpr int FIRST_TURN_ANGLE = 90;          // 1回目のターンの角度
  constexpr int SECOND_TURN_ANGLE = 100;        // 2回目のターンの角度
  constexpr int FIRST_TURN_PWM = 10;            // 1回目のターンのPWM値
  constexpr int SECOND_TURN_PWM = 40;           // 2回目のターンのPWM値
  constexpr int TARGET_BRIGHTNESS = 12;         //目標輝度
  constexpr double BLUE_LINE_DISTANCE = 280.0;  //青色のライン上を通過する距離
  constexpr double CURBE_DISTANCE = 750.0;  //カーブを曲がる間ライントレースする距離
  constexpr double BLOCK_CIRCLE_DISTANCE = 150.0;  //円を通過する距離
  constexpr double GREEN_CIRCLE_CENTER_POINT_DISTANCE
      = 40.0;  //緑の円に到着後円の中心に移動する距離
  constexpr double TO_BLACK_LINE_DISTANCE = 70.0;  //回頭後、円の中心から黒のラインまで前進する距離
  constexpr int TO_BLACK_LINE_PWM = 20;  //回頭後、円の中心から黒のラインまで前進するPWM値
  constexpr int TO_BLACK_BLOCK_PWM = 30;  //緑円から黒ブロックまでのライントレース時のPWM値
  constexpr double X_DISTANCE = 420.0;  //黒ブロックの初期位置から目的地までの縦の距離
  constexpr int X_PWM = 45;
  constexpr double Z_DISTANCE = 760.0;  //黒ブロックの初期位置から目的地までの横の距離
  constexpr int Z_PWM = 30;
  constexpr double BACK_BLACK_LINE_DISTANCE = 100;  //黒ブロック運搬後黒のラインまで戻る距離
  constexpr int BACK_BLACK_LINE_PWM = -30;
  const PidGain CURVE_GAIN(4, 2, 2.2);  //カーブのライントレースに使用するゲイン
  const PidGain STRAIGHT_GAIN(1.5, 1, 1.5);  //直進のライントレースに使用するゲイン
```

2021-07-15 16:37 UTC, yutotanaka24 commented on module/BlackBlockCarrier.cpp
> +  linetracer.runToColor(TARGET_BRIGHTNESS, RUN_PWM, RUN_GAIN);
定数が多すぎて少しでも数を減らそうと思い統一しました。結局定数化はやらないことになったので戻しとこうと思います。

2021-07-15 16:37 UTC, Takahiro55555 commented
> あとclang formatしてね。

自分の環境で、フォーマッタを適用をしたらプルリクの状態と同じになったんだけど、 @sugaken0528 の環境では違う感じ？

2021-07-15 16:39 UTC, sugaken0528 commented
コメントアウトのインデントが変だったからしてないものかと思った。
大丈夫ならいいや🙆‍♂️

2021-07-15 16:41 UTC, yutotanaka24 commented
> んー、確かに全部とはいったけどめちゃめちゃやったね。
> まず角度は定数にしなくて良い。ターンPWM値も定数じゃなくて良い。
> 最初は直進距離が定数であるものとそうでないものとでバラバラだったから統一化して欲しくて距離を定数にしてもらおうと思っただけ。
> TARGET_BRIGHTNESS, GAIN, RUN_GAINは確かに定数でいいかな。
> 
> で、RUN_PWM=50っていう直進で使ってるPWM値の定数があるにも関わらずTO_BLACK_LINE_PWM=20, TO_BLACK_BLOCK_PWM=30があるのはよくわからないね。
> RUN_PWMをBASE_PWMっていう定数名にして、これをPWM値の基準として、BASE_PWM-30とかBASE_PWM-20とかにするならわかる。
> 
> 今コードの見た目が結構気持ち悪いから、もう距離も定数化しなくていいや。
> 
> まとめ
> 定数にするのはTARGET_BRIGHTNESS, GAIN, RUN_GAIN, RUN_PWMのみで良いと思う。
> あとclang formatしてね。

了解しました。
1つ分からないことがあるんですけど、GAINとRUN_GAINがconstexprにするとエラーになるんですが、constでもいいでしょうか？

2021-07-15 16:45 UTC, Takahiro55555 commented on module/BlackBlockCarrier.cpp
> +  const PidGain RUN_GAIN(1.5, 1, 1.5);  //直進のライントレースに使用するゲイン
基本的には、このコメントの直前に出た @sugaken0528 の方針を基本的に採用すればよいと思います。

2021-07-15 16:50 UTC, sugaken0528 commented
constexprはコンパイル時点でわかる定数、constは実行しないとわからない定数だから、
GAINとRUN_GAINはconstじゃなきゃダメ

2021-07-15 17:23 UTC, Takahiro55555 approved these changes
![LGTM](https://image.lgtmoon.dev/134205)

2021-07-15 17:26 UTC, sugaken0528 approved these changes
おつかれさまんさ!!
遅くまでありがと!!!
![LGTM](https://image.lgtmoon.dev/134225)

2021-07-15 17:35 UTC, Hisataka-Hagiyama approved these changes
夜遅くに色々指摘してすみませんでした
LGTM

2021-07-15 17:49 UTC, uchyam reviewed
夜遅くに失礼します

2021-07-15 17:49 UTC, uchyam commented on module/BlackBlockCarrier.cpp
> +  const PidGain CURBE_GAIN(4, 2, 2.2);      //カーブのライントレースに使用するゲイン
CURVE_GAIN？

2021-07-16 02:43 UTC, miyashita64 approved these changes
LGTM

2021-07-16 03:05 UTC, merged