close #86 運搬するブロックの決定
KatLab-MiyazakiUniv/etrobocon2021 pull request #91
Opened 2021-07-08 07:41 UTC by hiroto0927

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点
RunningInfo.h
RunningInfo.cpp
BlockSelector.h
BlockSelector.cpp

# 動作テスト

## 実験方法

## 実験結果

## 添付資料

2021-07-08 08:26 UTC, miyashita64 commented on module/BlockSelector.h
> +  std::array<bool, BLOCK_LENGTH> carriedBlocks;
BingoAreaクラスから情報を得て算出

2021-07-08 08:28 UTC, miyashita64 commented on module/RunningInfo.h
> +
クラス名はRobotがいい

2021-07-08 08:33 UTC, miyashita64 commented on module/RunningInfo.h
> +
ちゃんとコメントを書く
数字ではなく方角順がいい(バラバラなのがわかりやすい)

2021-07-15 10:32 UTC, Takahiro55555 approved these changes
![LGTM](https://image.lgtmoon.dev/99428)

2021-07-15 11:24 UTC, mutotaka0426 requested changes
開放のリストも全体の流れ的にも良さそうだけど，一箇所だけあってるかわからんから確認よろしく
あとコメントのところも

2021-07-15 11:32 UTC, mutotaka0426 commented on module/BlockSelector.cpp
> +    if(!(arrivableCircles[targetCircleNumber] || OPEN_CIRCLE_ID[i][targetCircleNumber])) continue;
ごめん勘違いしてた
否定子全体にかかってたのか

2021-07-15 12:01 UTC, mutotaka0426 requested changes
今更で申し訳ないけどstaticにしてほしい
よろしく！

2021-07-15 12:01 UTC, mutotaka0426 commented on module/RoutePlanner.cpp
> +}
staticクラスにしたらこんな感じかな

```suggestion
void RoutePlanner::runBlockBingoArea()
{
  std::array<BLOCK_ID, static_cast<int>(BLOCK_ID::ID7) + 1> blockOrder;
  BingoArea bingoArea;
  DestinationList destinationList(bingoArea);
  BlockSelector blockSelector(bingoArea, destinationList);
  
  // ブロックの運搬順を取得する
  for(int i = static_cast<int>(BLOCK_ID::ID0); i < static_cast<int>(BLOCK_ID::ID7) + 1; i++) {
    blockOrder[i] = blockSelector.selectBlock();
  }
}
```

2021-07-15 13:06 UTC, Hisataka-Hagiyama reviewed
処理は問題ないと思うので、指摘されている経路計画クラスのstaticクラス化の変更が済み次第Approveします。

2021-07-15 13:06 UTC, Hisataka-Hagiyama commented on module/Robot.h
> +  Robot();
コンストラクタの実装部分は書いていないのであれば、 @mutotaka0426 がstatic化の提案をしている際に書いているように、
```suggestion
   /**
   * コンストラクタ
   * インスタンス化を禁止するためにpriveteにし、処理については記述していない
   */
  Robot();
```
に統一すると見やすいのかもしれません

2021-07-15 13:21 UTC, arimakaoru approved these changes
LGTM!!

2021-07-15 13:58 UTC, yutotanaka24 approved these changes

2021-07-15 14:15 UTC, sugaken0528 reviewed
処理はOKと思います!!
TF表みたいなやつ以外はかなり分かりやすかった!!
あとは指摘されたところをよろしく!!

2021-07-15 14:15 UTC, sugaken0528 commented on module/BlockSelector.cpp
> +    } }
これ初見じゃ理解に苦しむだろうね
来年困らんように説明加えてて欲しい
例えば走行体の初期位置はどこで、そこから取得できるブロックはこれであるため{T,T...}になるみたいな。

2021-07-15 14:19 UTC, sugaken0528 commented on module/BlockSelector.h
> +      OPEN_BLOCK_ID;
OPEN_CIRCLE_IDとOPEN_BLOCK_IDは定数にしといて!!
by 武藤

2021-07-15 14:20 UTC, sugaken0528 requested changes

2021-07-15 14:20 UTC, sugaken0528 commented on module/BlockSelector.h
> +      OPEN_BLOCK_ID;
OPEN_CIRCLE_IDとOPEN_BLOCK_IDは定数にしといて!!
by武藤

2021-07-15 14:58 UTC, miyashita64 commented on module/RoutePlanner.h
> +  BlockSelector blockSelector;
コメントと命名について、経路計画の上位にブロックビンゴエリア攻略がいたと思うので、経路計画するplanFullBingoRouteとしました。

2021-07-15 15:00 UTC, mutotaka0426 commented
追加されたjsonファイルって何？

2021-07-15 15:04 UTC, miyashita64 commented
> 追加されたjsonファイルって何？

すみません、紛れ込みです。
コミットから外しました。

2021-07-15 15:05 UTC, mutotaka0426 approved these changes
えるじーてぃーえむ

2021-07-15 15:07 UTC, Hisataka-Hagiyama approved these changes
LGTM

2021-07-15 16:44 UTC, mutotaka0426 requested changes
本当に申し訳ないんだけど，staticにしちゃだめだったから戻してください
ビンゴエリア攻略と勘違いしてた

あと今書いてある経路計画クラスでは，全てのブロックを運搬するまでの経路を求めるようになってると思うけど，ビンゴエリア攻略クラスが経路計画と動作変換を繰り返し呼び出すようにするから，経路計画では1つブロックを運ぶための経路を求めるようにする

ということで修正案として書いたやつでビルドとテスト通ったのは確認したからこんな感じがいい
何か分からなかったりおかしかったりしたら言ってください
変数とか関数とかの名づけ方は任せる

2021-07-15 16:44 UTC, mutotaka0426 commented on module/RoutePlanner.cpp
> +}
```suggestion
RoutePlanner::RoutePlanner(BingoArea& _bingoArea)
    : bingoArea(_bingoArea), destinationList(_bingoArea), blockSelector(_bingoArea, destinationList)
{
}

void RoutePlanner::planBingoRoute()
{
  // 運搬するブロックを決定する
  BLOCK_ID blockOrder = blockSelector.selectBlock();
  
  // 現在地からブロックまでの経路を探索する
  
  // ブロックからブロックサークルまでの経路を探索する
  
  // 2つの経路を足し合わせる???
  // return 経路
}
```

2021-07-16 02:42 UTC, mutotaka0426 approved these changes
良いと思います！
めっちゃ変更させてごめん！
![LGTM](https://image.lgtmoon.dev/134257)

2021-07-16 05:17 UTC, sugaken0528 approved these changes

2021-07-16 05:17 UTC, merged