close #4 シミュレータの自動実行
KatLab-MiyazakiUniv/etrobocon2021 pull request #92
Opened 2021-07-15 06:17 UTC by Takahiro55555

動作確認

# チェックリスト

- [ ] clang-format している
- [ ] コーディング規約に準じている
- [ ] チケットの完了条件を満たしている

# 変更点

# 動作テスト

## 実験方法

## 実験結果

## 添付資料

2021-07-16 10:16 UTC, arimakaoru approved these changes
LGTM!!
疑問点
- プルリクに対して新しくコミットした場合や、ドラフトプルリクを出した場合も、シミュレータテストは実行される？
- シミュレータテストを実行したときの動画は、どこかに保存している？

2021-07-16 10:16 UTC, arimakaoru commented on .github/workflows/sim-test.yaml
> +    # 走行タイタイムをコメントとして載せる
```suggestion
    # 走行タイムをコメントとして載せる
```

2021-07-16 15:23 UTC, Hisataka-Hagiyama approved these changes
![LGTM](https://image.lgtmoon.dev/134371)

2021-07-16 16:13 UTC, Takahiro55555 commented
@arimakaoru 
> * プルリクに対して新しくコミットした場合や、ドラフトプルリクを出した場合も、シミュレータテストは実行される？

Yes

> * シミュレータテストを実行したときの動画は、どこかに保存している？後から見れる？

現在、保存は行っていません。
ただし、このイテレーションの前半には、[シュミレータの動画を添付する #36](https://github.com/KatLab-MiyazakiUniv/etrobocon2021/issues/36)に取り掛かる予定です。

2021-07-17 11:51 UTC, sugaken0528 approved these changes

2021-07-19 01:21 UTC, arimakaoru commented
シミュレータテストが失敗してるけど、大丈夫？

2021-07-20 01:17 UTC, mutotaka0426 approved these changes
![LGTM](https://image.lgtmoon.dev/134541)

2021-07-21 14:40 UTC, korosuke613 commented on .github/workflows/sim-test.yaml
> +    runs-on: self-hosted
こんにちは。横から失礼します。シミュレータによる自動テストはとても良い取り組みですね。
それはそれとして、self-hosted runner を使っているみたいだったので、お節介かもしれませんがセキュリティ上の注意と対策方法についてを書きに来ました。（既に知ってたら申し訳ないです。）長くなってしまったので、適当に読んでみてください。

---

おそらくご存知かとは思いますが、**self-hosted runnerをpublicリポジトリで利用することにはセキュリティ上のリスクが伴います。** publicリポジトリの場合forkしてプルリクエストを送ることが可能なので、悪意あるワークフローをプルリクエスト内に含めることでself-hosted runnerに利用しているマシン上で任意のコードを実行できてしまいます。（[参考](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#self-hosted-runner-security-with-public-repositories)）

しかし、このリポジトリをprivateにするべきだと言っているわけではありません。最近GitHubではfork先からの初めてのプルリクエストでGitHub Actionsを動かすのに承認が必要となりました。（[参考](https://github.blog/changelog/2021-04-22-github-actions-maintainers-must-approve-first-time-contributor-workflow-runs/)）

したがって、fork先からのプルリクエストが来た場合に、勝手にself-hosted runnerが動かされることはありません。初回の場合は承認が必要です。しかし一度承認してマージされた後に、同一アカウントから悪意あるプルリクエストが来てしまった場合、やはり悪意あるコードが実行されてしまいます。

そのため、万が一のことが無いように、fork先からのプルリクエストに対するactionsの実行には常に承認が必要とする設定を行うことをお勧めします。下図の「Require approval for all outside collaborators」です。（ https://github.com/KatLab-MiyazakiUniv/etrobocon2021/settings/actions ）
<img width="773" alt="スクリーンショット 2021-07-21 22 47 28" src="https://user-images.githubusercontent.com/20027695/126500123-2d107ff2-e48d-4ce6-90aa-04ddbad75a2d.png">

ただ、KatLab-MiyazakiUniv に所属しているアカウントはデフォルトでこのリポジトリのwrite権限を持っているため、forkせずにプルリクエストを作ることができ、承認無しでActionsを実行できてしまいます。現在etロボコンに参加しているメンバーはもちろん信頼できますが、既に卒業されている方々はその限りではないと思います。（例：僕はこのリポジトリのwrite権限を持っているため、self-hosted runnerを経由して学内ネットワークに侵入できてしまいます。）

もちろんそんなことする人はこのOrganizationにいないと思いますが、やはり安全面を考えると対策しておくことをお勧めします。現在 KatLab-MiyazakiUniv のBase RoleはWriteであるため、KatLab-MiyazakiUniv に所属しているアカウントはKatLab-MiyazakiUniv配下にあるリポジトリのWrite権限を持っています。対策としては、OrganizationのBase RoleをReadにして（[参考](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/setting-base-permissions-for-an-organization)）、開発メンバのみにWrite権限を与えることもできます。しかし、この方法はetrobocon2021以外のリポジトリも影響されてしまいます。

もう一つの方法として、KatLab-MiyazakiUnivに所属している人全員が入ったTeamを作り、etrobocon2021のManage accessからRead権限に限定する方法もあります。この方法だとAdmin以外の全員がRead権限のみを持つことになります。そして開発メンバにはWrite権限を与えれば開発メンバのみがWrite権限を持てます。（でもこの方法本当にできるか未確認です。もしかしたらBase RoleのWrite権限が優先されちゃうかも）

最後に、KatLab-MiyazakiUnivのOwnerは全てのリポジトリに対してAdmin権限を持っているため、上記のような方法で縛ることができません。そのため、Ownerは必要最低限の信頼できる人物にするべきです。これに関してはしっかりと棚卸ししているみたいで良いです。大丈夫そうですね。（自分もOwner外されてたのさっき知った。）

最後の最後に、self-hosted runnerをOrganizationに対して登録してしまっている場合、他のリポジトリでも同様のリスクが発生してしまうので、その場合はこのリポジトリに対してself-hosted runnerを登録することを強くお勧めします。

2021-07-22 06:29 UTC, Tatsumi0000 requested changes
v2がよさそうです！

2021-07-22 06:29 UTC, Tatsumi0000 commented on .github/workflows/sim-test.yaml
> +        uses: actions/checkout@v1
```suggestion
        uses: actions/checkout@v2
```
ここは特に理由がなければv2がよさそうです．最新が最高なので！

ref. https://github.com/marketplace/actions/checkout

2021-07-22 09:54 UTC, Takahiro55555 commented on .github/workflows/sim-test.yaml
> +    runs-on: self-hosted
コメントありがとうございます。
特に、「Require approval for all outside collaborators」関しては知りませんでした。

以下、回答です。

- > そのため、万が一のことが無いように、fork先からのプルリクエストに対するactionsの実行には常に承認が必要とする設定を行うことをお勧めします。
    - `Require approval for all outside collaborators` に変更しました。

- >self-hosted runnerを経由して学内ネットワークに侵入できてしまいます
    - 万が一のことを考え、self-hosted runner が動作しているマシン（ネットワーク）から学内ネットワークへの通信はすべて遮断しています。

- >KatLab-MiyazakiUniv に所属しているアカウントはデフォルトでこのリポジトリのwrite権限を持っているため、forkせずにプルリクエストを作ることができ、承認無しでActionsを実行できてしまいます。
    - 以前 @arimakaoru と話し合った際、KatLab-MiyazakiUniv のメンバーを基本的に信用するということで Base Role を Write にしていました。しかし、アカウントの乗っ取りが発生する可能性などを考慮し、Base Role を Read に変更することにしました。何らかの不都合が生じた場合、その都度解決する方針です。

- >self-hosted runnerをOrganizationに対して登録してしまっている場合、他のリポジトリでも同様のリスクが発生してしまうので、その場合はこのリポジトリに対してself-hosted runnerを登録することを強くお勧めします。
    - self-hosted runner は `KatLab-MiyazakiUniv/etrobocon2021` に対して登録しており、他のリポジトリからは利用できないと認識しています。

今後も、気づいた点などがあれば指摘していただけると幸いです。

2021-07-22 12:01 UTC, Tatsumi0000 commented
v2になっててよさそう☻🙆

2021-07-24 10:58 UTC, korosuke613 commented on .github/workflows/sim-test.yaml
> +    runs-on: self-hosted
`Require approval for all outside collaborators` は特にアナウンスがなく設定できるようになってたし、ドキュメントで見つからない（たぶん）ので、案外知らない人が多そうです。

> 万が一のことを考え、self-hosted runner が動作しているマシン（ネットワーク）から学内ネットワークへの通信はすべて遮断しています。

万が一に備えていてとても良いですね。

返信ありがとうございます。お役に立てたようで良かったです。

2021-07-29 07:07 UTC, uchyam approved these changes
LGTM

2021-07-29 07:15 UTC, miyashita64 approved these changes
LGTM!!

2021-07-29 07:27 UTC, merged